{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvdirection\/cancelroute()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Cancel all request."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelRoute"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]]},"metadata":{"title":"cancelRoute()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelRoute","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"NVDirectionKit"}],"externalID":"s:14NVDirectionKit0A0C11cancelRouteyyF","role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/cancelRoute()"},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/cancelRoute()":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/cancelRoute()","title":"cancelRoute()","abstract":[{"type":"text","text":"Cancel all request."}],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvdirection\/cancelroute()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelRoute"},{"text":"()","kind":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"url":"\/documentation\/nvdirectionkit\/nvdirection","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","navigatorTitle":[{"kind":"identifier","text":"NVDirection"}],"title":"NVDirection","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"type":"topic","title":"NVDirectionKit","kind":"symbol","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.5.0","type":"text"}],"url":"\/documentation\/nvdirectionkit","role":"collection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"}},"variantOverrides":[{"patch":[{"op":"replace","value":"NVDirection","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title"},{"value":[{"kind":"identifier","text":"NVDirection"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NVDirection"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}