{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"role":"symbol","modules":[{"name":"NVDirectionKit"}],"externalID":"c:@M@NVDirectionKit@objc(cs)NVDirection(im)init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init"},"kind":"symbol","identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/init","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nvdirectionkit\/nvdirection\/init"]}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]]},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"url":"\/documentation\/nvdirectionkit\/nvdirection","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","navigatorTitle":[{"kind":"identifier","text":"NVDirection"}],"title":"NVDirection","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"type":"topic","title":"NVDirectionKit","kind":"symbol","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.5.0","type":"text"}],"url":"\/documentation\/nvdirectionkit","role":"collection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/init":{"abstract":[],"url":"\/documentation\/nvdirectionkit\/nvdirection\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","kind":"symbol","title":"init","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/init"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title","value":"NVDirection"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments","op":"replace","value":[{"text":"NVDirection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/navigatorTitle","value":[{"text":"NVDirection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}