{"metadata":{"externalID":"s:14NVDirectionKit23NVibeWalkingInformationC12startAddressAA0C8LocationCvp","modules":[{"name":"NVDirectionKit"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startAddress"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"}],"title":"startAddress","role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"abstract":[{"type":"text","text":"The  start location of the walking multimodal step."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier","text":"NVibeLocation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibewalkinginformation\/startaddress"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/startAddress","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Getting the walking information attributes","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/endAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/walkingMode","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode"],"anchor":"Getting-the-walking-information-attributes"}],"sections":[],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/endAddress":{"abstract":[{"type":"text","text":"The  end location of the walking multimodal step."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"endAddress","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"}],"role":"symbol","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/endaddress","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/endAddress","title":"endAddress","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/startAddress":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/startAddress","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startAddress"},{"kind":"text","text":": "},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"}],"title":"startAddress","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The  start location of the walking multimodal step."}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/startaddress"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation":{"title":"NVibeWalkingInformation","navigatorTitle":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeWalkingInformation"}],"abstract":[{"text":"The walking information describing a walking multimodal step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/Mode":{"abstract":[{"type":"text","text":"Constants that describe the mode of the walking multimodal step."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mode"}],"role":"symbol","navigatorTitle":[{"text":"Mode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/mode","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode","title":"NVibeWalkingInformation.Mode","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"title":"NVibeLocation","navigatorTitle":[{"text":"NVibeLocation","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeLocation"}],"abstract":[{"text":"The address and coordinates of a location.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/walkingMode":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/walkingMode","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"walkingMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeWalkingInformation","text":"NVibeWalkingInformation","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14NVDirectionKit23NVibeWalkingInformationC4ModeO","kind":"typeIdentifier","text":"Mode"}],"title":"walkingMode","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The mode of the walking multimodal step."}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/walkingmode"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"type":"topic","title":"NVDirectionKit","kind":"symbol","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.5.0","type":"text"}],"url":"\/documentation\/nvdirectionkit","role":"collection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/title","value":"NVibeWalkingInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/fragments","value":[{"text":"NVibeWalkingInformation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/navigatorTitle","value":[{"text":"NVibeWalkingInformation","kind":"identifier"}],"op":"replace"},{"value":"NVibeLocation","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","op":"replace"},{"op":"replace","value":[{"text":"NVibeLocation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments"},{"value":[{"text":"NVibeLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}