{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withObstacle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withObstacle","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/language","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withCrossing","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/forbiddenObstacles","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withInformationPoint","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withAlternativeGeometry","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/viaLinks","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/transitionData"],"anchor":"Getting-the-option-attributes","title":"Getting the option attributes"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/nvdirectionkit\/nviberouteoption\/withobstacle"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","modules":[{"name":"NVDirectionKit"}],"title":"withObstacle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withObstacle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Instance Property","externalID":"s:14NVDirectionKit16NVibeRouteOptionC12withObstacleSbvp","symbolKind":"property"},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/withCrossing":{"abstract":[],"url":"\/documentation\/nvdirectionkit\/nviberouteoption\/withcrossing","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withCrossing","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCrossing"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"withCrossing","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/withObstacle":{"abstract":[],"url":"\/documentation\/nvdirectionkit\/nviberouteoption\/withobstacle","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withObstacle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"withObstacle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"withObstacle","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/withAlternativeGeometry":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withAlternativeGeometry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"withAlternativeGeometry","url":"\/documentation\/nvdirectionkit\/nviberouteoption\/withalternativegeometry","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withAlternativeGeometry","abstract":[]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","abstract":[{"type":"text","text":"The option for walking route."}],"type":"topic","role":"symbol","url":"\/documentation\/nvdirectionkit\/nviberouteoption","navigatorTitle":[{"text":"NVibeRouteOption","kind":"identifier"}],"title":"NVibeRouteOption","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteOption"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/forbiddenObstacles":{"url":"\/documentation\/nvdirectionkit\/nviberouteoption\/forbiddenobstacles","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/forbiddenObstacles","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forbiddenObstacles","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"type":"topic","kind":"symbol","title":"forbiddenObstacles","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/transitionData":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transitionData","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitionData","text":"NVibeTransitionData"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","title":"transitionData","url":"\/documentation\/nvdirectionkit\/nviberouteoption\/transitiondata","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/transitionData","abstract":[]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/withInformationPoint":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withInformationPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"withInformationPoint","url":"\/documentation\/nvdirectionkit\/nviberouteoption\/withinformationpoint","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/withInformationPoint","abstract":[]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/viaLinks":{"abstract":[],"url":"\/documentation\/nvdirectionkit\/nviberouteoption\/vialinks","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/viaLinks","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viaLinks"},{"text":": [","kind":"text"},{"text":"Link","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)Link","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"viaLinks","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption/language":{"abstract":[],"url":"\/documentation\/nvdirectionkit\/nviberouteoption\/language","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption\/language","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"language"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"language","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"NVibeRouteOption","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/fragments","op":"replace","value":[{"text":"NVibeRouteOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/navigatorTitle","op":"replace","value":[{"text":"NVibeRouteOption","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}