{"primaryContentSections":[{"content":[{"anchor":"Overview","text":"Overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can calculate route between two locations and set different parameter based on your need."}]},{"inlineContent":[{"text":"A ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute"},{"type":"text","text":" contains one "},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","isActive":true,"type":"reference"},{"type":"text","text":" which contains two or more "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep"},{"type":"text","text":". Each "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep"},{"type":"text","text":" refers to an instruction and you will always get at least 2 of them (the start and the arrival)."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Every "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep"},{"text":" can be represented by a coordinate (where the instruction need to be done) and a geometry (to draw the path between the instruction and the next one).","type":"text"}]},{"text":"Calculate a route","type":"heading","level":2,"anchor":"Calculate-a-route"},{"inlineContent":[{"text":"To calculate route, you need to use the method ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withAlternativePolyline:completion:)","isActive":true},{"type":"text","text":" with a start and end "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You will receive a result or a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError"},{"text":". The result contains 3 values. ","type":"text"},{"type":"codeVoice","code":"route"},{"text":" is your calculated ","type":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","type":"reference","isActive":true},{"type":"text","text":", "},{"type":"codeVoice","code":"startingDirection"},{"type":"text","text":" value represents the angle towards the start of the route and "},{"type":"codeVoice","code":"solutionFound"},{"type":"text","text":" value indicates if the result contains good crossing pathing."}]},{"syntax":"swift","code":["import NVDirectionKit","import CoreLocation","","class MyClass: UIViewController {","","    override func viewDidLoad() {","        let origin = CLLocationCoordinate2D(latitude: 48.85934519646515, longitude: 2.3790224217764826)","        let destination = CLLocationCoordinate2D(latitude: 48.85869580049223, longitude: 2.373062553499055)","        ","        NVDirection.shared.getNavigationRoute(from: NVibeLocation(address: \"7 Avenue Parmentier\", position: origin), to: NVibeLocation(address: \"Pépinière 27\", position: destination)) { (result, error) in","            guard result != nil, error == nil else {","                \/\/You will receive an error if the route calculation fails. More detail about the error in the error object.","                return","            }","            \/\/You receive the calculated route here and additional data.","            result.route \/\/NVibeRoute","            result.startingDirection \/\/CLLocationDirection","            result.solutionFound \/\/Bool","        }","    }","}"],"type":"codeListing"},{"anchor":"Set-the-departure-side-street","type":"heading","text":"Set the departure side street","level":2},{"type":"paragraph","inlineContent":[{"text":"When you request a route, you can also add a departure ","type":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","isActive":true,"type":"reference"},{"text":" to tell if you want that the calculated route starts from the left or the right side.","type":"text"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If no side street is set, the starting side will be set to the opposite of the first turn instruction. For exemple, if the next turn instruction after the departure is left, the starting side will be set to right."}]}],"type":"aside","style":"important","name":"Important"},{"type":"codeListing","syntax":"swift","code":["NVDirection.shared.getNavigationRoute(from: start, to: end, sideStreet: .LEFT) { (result, error) in","    guard result != nil, error == nil else {","        \/\/You will receive an error if the route calculation fails. More detail about the error in the error object.","        return","    }","    \/\/You receive the calculated route here and additional data.","    result.route \/\/NVibeRoute","    result.startingDirection \/\/CLLocationDirection","    result.solutionFound \/\/Bool","}"]},{"text":"Set the language of instruction","level":2,"type":"heading","anchor":"Set-the-language-of-instruction"},{"type":"paragraph","inlineContent":[{"text":"When you calculate a route, you can change the language of the instruction.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Available languages are English (en), French (fr), Dutch (nl), Spanish (es), German (de). The default language is English.","type":"text"}]},{"code":["NVDirection.shared.getNavigationRoute(from: start, to: end, language: \"en\") { (result, error) in","    guard result != nil, error == nil else {","        \/\/You will receive an error if the route calculation fails. More detail about the error in the error object.","        return","    }","    \/\/You receive the calculated route here and additional data.","    result.route \/\/NVibeRoute","    result.startingDirection \/\/CLLocationDirection","    result.solutionFound \/\/Bool","}"],"syntax":"swift","type":"codeListing"},{"anchor":"Get-an-alternative-geometry","text":"Get an alternative geometry","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"When you calculate a route, you can request an alternative geometry. The alternative geometry follows the sidewalk instead of the center of the route.","type":"text"}]},{"code":["NVDirection.shared.getNavigationRoute(from: start, to: end, withAlternativePolyline: true) { (result, error) in","    guard result != nil, error == nil else {","        \/\/You will receive an error if the route calculation fails. More detail about the error in the error object.","        return","    }","    \/\/You receive the calculated route here and additional data.","    result.route.alternativeGeometry","}"],"type":"codeListing","syntax":"swift"},{"level":2,"type":"heading","text":"Get obstacles along the walking route and avoid them","anchor":"Get-obstacles-along-the-walking-route-and-avoid-them"},{"type":"paragraph","inlineContent":[{"text":"When you calculate a route, you can request obstacles along the walking route.","type":"text"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Obstacles are actually available on specific area so the majority of walking route will not contain any obstacles.","type":"text"}]}],"style":"important","name":"Important","type":"aside"},{"code":["NVDirection.shared.getNavigationRoute(from: start, to: end, withObstacle: true) { (result, error) in","    guard result != nil, error == nil else {","        \/\/You will receive an error if the route calculation fails. More detail about the error in the error object.","        return","    }","    \/\/You receive the calculated route here and additional data.","    for leg in result.route.legs {","        for step in leg.steps {","            guard let obstacles = step.obstacles else { continue }","            for obstacle in obstacles {","                obstacle.id","            }","        }","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"Then, you can calculate a new route by adding forbidden obstacles with their ","type":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/id","type":"reference","isActive":true},{"text":".","type":"text"}]},{"style":"important","name":"Important","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Forbidden obstacles will only change the crossing path along the route if possible.","type":"text"}]}]},{"type":"codeListing","syntax":"swift","code":["NVDirection.shared.getNavigationRoute(from: start, to: end, withObstacle: true, forbiddenObstacles: [obstacle.id]) { (result, error) in","    guard result != nil, error == nil else {","        \/\/You will receive an error if the route calculation fails. More detail about the error in the error object.","        return","    }","    \/\/You receive the calculated route here and additional data.","    for leg in result.route.legs {","        for step in leg.steps {","            guard let obstacles = step.obstacles else { continue }","            for obstacle in obstacles {","                obstacle.id","            }","        }","    }","}"]},{"type":"heading","anchor":"Get-only-the-starting-direction-of-a-route","text":"Get only the starting direction of a route","level":2},{"inlineContent":[{"text":"If you want only the starting direction of a route, you can use ","type":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:completion:)","type":"reference","isActive":true},{"text":" instead. It will count as a route calculation for the API but without crossing so it will be faster. If you have already your ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute"},{"type":"text","text":", just get the starting direction from the object data."}],"type":"paragraph"},{"code":["NVDirection.shared.getStartingDirection(from: start, to: end) { (direction, error) in","    guard result != nil, error == nil else {","        \/\/You will receive an error if the route calculation fails. More detail about the error in the error object.","        return","    }","    \/\/You receive the direction here.","    direction \/\/CLLocationDirection","}"],"syntax":"swift","type":"codeListing"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute"},"metadata":{"title":"Getting walking route","modules":[{"name":"NVDirectionKit"}],"roleHeading":"Article","role":"article"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"],"generated":true,"anchor":"Essentials","title":"Essentials"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"abstract":[{"text":"Retrieve a walking route between two locations.","type":"text"}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/getroute"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nvdirectionkit\/getroute"]}],"sections":[],"kind":"article","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RouteError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RouteError"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/routeerror","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError","title":"RouteError","abstract":[{"text":"Constants that describe error related to walking route calculation.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withAlternativePolyline:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getNavigationRoute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sideStreet","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14NVDirectionKit10SideStreetO","text":"SideStreet"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"language"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"withObstacle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"forbiddenObstacles","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"withAlternativePolyline"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((route","kind":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"text":", startingDirection","kind":"text"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CLLocationDirection","kind":"typeIdentifier","text":"CLLocationDirection"},{"kind":"text","text":", solutionFound"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")?, ","kind":"text"},{"text":"RouteError","preciseIdentifier":"s:14NVDirectionKit10RouteErrorO","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Returns a walking route.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withAlternativePolyline:completion:)","role":"symbol","kind":"symbol","title":"getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withAlternativePolyline:completion:)","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getnavigationroute(from:to:sidestreet:language:withobstacle:forbiddenobstacles:withalternativepolyline:completion:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg":{"navigatorTitle":[{"kind":"identifier","text":"NVibeLeg"}],"type":"topic","kind":"symbol","title":"NVibeLeg","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeLeg","kind":"identifier"}],"url":"\/documentation\/nvdirectionkit\/nvibeleg","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","abstract":[{"type":"text","text":"The walking leg inside walking route."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"type":"topic","title":"NVDirectionKit","kind":"symbol","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.5.0","type":"text"}],"url":"\/documentation\/nvdirectionkit","role":"collection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"title":"NVibeLocation","navigatorTitle":[{"text":"NVibeLocation","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeLocation"}],"abstract":[{"text":"The address and coordinates of a location.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"type":"topic","kind":"symbol","title":"NVibeStep","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeStep","kind":"identifier"}],"url":"\/documentation\/nvdirectionkit\/nvibestep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","abstract":[{"type":"text","text":"The walking step inside walking leg."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle/id":{"title":"id","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","abstract":[{"text":"The id of the obstacle.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibeobstacle\/id","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/id"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"navigatorTitle":[{"text":"NVibeRoute","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NVibeRoute","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeRoute"}],"url":"\/documentation\/nvdirectionkit\/nviberoute","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","abstract":[{"type":"text","text":"The walking route received when requesting walking route."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideStreet"}],"navigatorTitle":[{"text":"SideStreet","kind":"identifier"}],"abstract":[{"text":"The side of the street.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/sidestreet","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","title":"SideStreet","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"url":"\/documentation\/nvdirectionkit\/nvdirection","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","navigatorTitle":[{"kind":"identifier","text":"NVDirection"}],"title":"NVDirection","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/GetStarted":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","abstract":[{"type":"text","text":"Configure your app to be able to use the framework."}],"kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/getstarted","role":"article","title":"Get started"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getStartingDirection(from:to:completion:)":{"title":"getStartingDirection(from:to:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getStartingDirection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:14NVDirectionKit10RouteErrorO","kind":"typeIdentifier","text":"RouteError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"text":"Returns the starting direction of a walking route.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvdirection\/getstartingdirection(from:to:completion:)","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:completion:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/GetMultimodalRoute":{"abstract":[{"type":"text","text":"Retrieve a multimodal route including transit between two locations."}],"type":"topic","kind":"article","title":"Getting multimodal route","url":"\/documentation\/nvdirectionkit\/getmultimodalroute","role":"article","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/topicSections","value":null},{"value":[{"title":"Essentials","generated":true,"anchor":"Essentials","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/title","value":"NVibeLeg","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/fragments","value":[{"text":"NVibeLeg","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeLeg"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","value":"NVibeLocation"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"kind":"identifier","text":"NVibeLocation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/navigatorTitle","op":"replace","value":[{"text":"NVibeLocation","kind":"identifier"}]},{"value":"NVibeStep","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title"},{"value":[{"kind":"identifier","text":"NVibeStep"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/navigatorTitle","value":[{"text":"NVibeStep","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title","op":"replace","value":"NVibeRoute"},{"op":"replace","value":[{"text":"NVibeRoute","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/navigatorTitle","value":[{"text":"NVibeRoute","kind":"identifier"}]},{"value":"NVDirection","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title","op":"replace"},{"value":[{"kind":"identifier","text":"NVDirection"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/navigatorTitle","value":[{"text":"NVDirection","kind":"identifier"}]}]}]}