{"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH"],"title":"Conforms To"}],"metadata":{"roleHeading":"Class","modules":[{"name":"NVDirectionKit"}],"externalID":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStepInformation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"symbolKind":"class","title":"NVibeMultimodalStepInformation"},"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/mode-swift.property","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/getWalkingInformation()","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/getTransitInformation()","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/Mode-swift.enum"],"anchor":"Getting-the-multimodal-step-information-attributes","title":"Getting the multimodal step information attributes"}],"seeAlsoSections":[{"anchor":"MultimodalRoute","title":"MultimodalRoute","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError"],"generated":true}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The information describing a multimodal step."}],"references":{"doc://com.nvibe.NVDirectionKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.nvibe.NVDirectionKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.nvibe.NVDirectionKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.nvibe.NVDirectionKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation":{"title":"NVibeWalkingInformation","navigatorTitle":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeWalkingInformation"}],"abstract":[{"text":"The walking information describing a walking multimodal step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"type":"topic","title":"NVDirectionKit","kind":"symbol","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.5.0","type":"text"}],"url":"\/documentation\/nvdirectionkit","role":"collection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeMultimodalStep","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeMultimodalStep","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The multimodal step inside multimodal route.","type":"text"}],"type":"topic","title":"NVibeMultimodalStep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation/mode-swift.property":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/mode-swift.property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeMultimodalStepInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStepInformation"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14NVDirectionKit30NVibeMultimodalStepInformationC4ModeO","text":"Mode","kind":"typeIdentifier"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/mode-swift.property","abstract":[{"text":"The mode of the multimodal step.","type":"text"}],"title":"mode","type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation/getWalkingInformation()":{"title":"getWalkingInformation()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getWalkingInformation"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"NVibeWalkingInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeWalkingInformation"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation"},{"text":" describing the multimodal step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/getwalkinginformation()","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/getWalkingInformation()","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation/Mode-swift.enum":{"navigatorTitle":[{"text":"Mode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/Mode-swift.enum","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/mode-swift.enum","role":"symbol","title":"NVibeMultimodalStepInformation.Mode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Mode"}],"abstract":[{"text":"Constants that describe the mode of the multimodal step.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation":{"navigatorTitle":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation","role":"symbol","title":"NVibeMultimodalStepInformation","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalStepInformation"}],"abstract":[{"text":"The information describing a multimodal step.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError":{"title":"MultimodalError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimodalError"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultimodalError"}],"url":"\/documentation\/nvdirectionkit\/multimodalerror","abstract":[{"type":"text","text":"Constants that describe error related to multimodal route calculation."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation/getTransitInformation()":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/getTransitInformation()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTransitInformation"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation","text":"NVibeTransitInformation","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/gettransitinformation()","abstract":[{"text":"Returns a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation"},{"type":"text","text":" describing the multimodal step."}],"title":"getTransitInformation()","type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeTransitInformation","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitInformation"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","title":"NVibeTransitInformation","abstract":[{"text":"The walking information describing a walking multimodal step.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute":{"type":"topic","title":"NVibeMultimodalRoute","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalRoute"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute","role":"symbol","navigatorTitle":[{"text":"NVibeMultimodalRoute","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","abstract":[{"text":"The multimodal route received when requesting multimodal route.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"},"doc://com.nvibe.NVDirectionKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"NVibeMultimodalStepInformation","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"op":"replace"},{"value":null,"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation"],"title":"Inherited By","kind":"relationships","type":"inheritedBy"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"generated":true,"anchor":"MultimodalRoute","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation"],"title":"MultimodalRoute"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalStepInformation"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"NVibeWalkingInformation","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/title"},{"value":[{"text":"NVibeWalkingInformation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/fragments"},{"value":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/navigatorTitle","op":"replace"},{"value":"NVibeMultimodalStep","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments","op":"replace","value":[{"text":"NVibeMultimodalStep","kind":"identifier"}]},{"op":"replace","value":[{"text":"NVibeMultimodalStep","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/title","value":"NVibeMultimodalStepInformation"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/fragments","op":"replace","value":[{"kind":"identifier","text":"NVibeMultimodalStepInformation"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/navigatorTitle","value":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"op":"replace"},{"value":"NVibeTransitInformation","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"NVibeTransitInformation"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/fragments"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/navigatorTitle","value":[{"text":"NVibeTransitInformation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/title","value":"NVibeMultimodalRoute"},{"value":[{"kind":"identifier","text":"NVibeMultimodalRoute"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/navigatorTitle","value":[{"text":"NVibeMultimodalRoute","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}