{"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH"]}],"seeAlsoSections":[{"generated":true,"anchor":"Global","title":"Global","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet"]}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"kind":"symbol","abstract":[{"type":"text","text":"The address and coordinates of a location."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NVibeLocation","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","isActive":true},{"type":"text","text":" object contains the optional address of the location, the position coordinate of the location and the optional access coordinate of the location."}]},{"inlineContent":[{"type":"text","text":"Generally, the position coordinate represents the coordinate of the building or place while the access coordinate represents the coordinate on the route to enter\/exit the location. Most of routing engine use the nearest route from the given start and end coordinate to determine the departure and arrival coordinate but sometimes, the nearest route is not the real departure or arrival. Use access coordinate to be sure that calculated route will start and end from the right departure and arrival."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibelocation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nvdirectionkit\/nvibelocation"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeLocation"}],"symbolKind":"class","title":"NVibeLocation","roleHeading":"Class","externalID":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeLocation"}],"modules":[{"name":"NVDirectionKit"}]},"topicSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(address:position:access:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(address:position:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(position:access:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(position:)"],"anchor":"Creating-a-location","title":"Creating a location"},{"anchor":"Getting-the-location-attributes","title":"Getting the location attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/address","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/position","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/access"]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"title":"NVibeLocation","navigatorTitle":[{"text":"NVibeLocation","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeLocation"}],"abstract":[{"text":"The address and coordinates of a location.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation/init(position:access:)":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(position:access:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"access","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(position:access:)","abstract":[{"text":"Creates a location object with the specified position and access values.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation\/init(position:access:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation/position":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"title":"position","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/position","abstract":[{"type":"text","text":"The position coordinate of the location."}],"type":"topic","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibelocation\/position","role":"symbol"},"doc://com.nvibe.NVDirectionKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation/init(address:position:access:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"address","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"access"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(address:position:access:)","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(address:position:access:)","abstract":[{"type":"text","text":"Creates a location object with the specified address, position and access values."}],"type":"topic","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibelocation\/init(address:position:access:)","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation/init(position:)":{"kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(position:)","title":"init(position:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Creates a location object with the specified position values."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation\/init(position:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation/access":{"abstract":[{"type":"text","text":"The access coordinate of the location."}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"access","kind":"identifier"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"title":"access","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/access","url":"\/documentation\/nvdirectionkit\/nvibelocation\/access","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"type":"topic","title":"NVDirectionKit","kind":"symbol","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.5.0","type":"text"}],"url":"\/documentation\/nvdirectionkit","role":"collection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"},"doc://com.nvibe.NVDirectionKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject","title":"NSObject"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle":{"title":"NVibeObstacle","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeObstacle","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"The obstacle along a route.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibeobstacle","navigatorTitle":[{"text":"NVibeObstacle","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle"},"doc://com.nvibe.NVDirectionKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation/init(address:position:)":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Creates a location object with the specified address and position values."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(address:position:)","title":"init(address:position:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"address","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":")"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation\/init(address:position:)","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideStreet"}],"navigatorTitle":[{"text":"SideStreet","kind":"identifier"}],"abstract":[{"text":"The side of the street.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/sidestreet","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","title":"SideStreet","type":"topic"},"doc://com.nvibe.NVDirectionKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","title":"NVibeIndoorLocation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeIndoorLocation"}],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The address and coordinates of a indoor location."}],"navigatorTitle":[{"kind":"identifier","text":"NVibeIndoorLocation"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation/address":{"url":"\/documentation\/nvdirectionkit\/nvibelocation\/address","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"address"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"address","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/address","abstract":[{"text":"The address of the location.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"NVibeLocation"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"NVibeLocation","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"NVibeLocation","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"value":[{"anchor":"Global","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle"],"title":"Global"}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeLocation","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"value":"NVibeLocation","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"kind":"identifier","text":"NVibeLocation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/navigatorTitle","op":"replace","value":[{"text":"NVibeLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/title","value":"NVibeObstacle"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/fragments","value":[{"kind":"identifier","text":"NVibeObstacle"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/navigatorTitle","op":"replace","value":[{"text":"NVibeObstacle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/title","value":"NVibeIndoorLocation"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/fragments","value":[{"kind":"identifier","text":"NVibeIndoorLocation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/navigatorTitle","op":"replace","value":[{"text":"NVibeIndoorLocation","kind":"identifier"}]}]}]}