{"metadata":{"modules":[{"name":"NVDirectionKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeObstacle","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeObstacle"}],"externalID":"c:@M@NVDirectionKit@objc(cs)NVibeObstacle","roleHeading":"Class","symbolKind":"class","title":"NVibeObstacle"},"topicSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/id","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/type","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/position","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/projection","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/photo"],"title":"Getting the obstacle attributes","anchor":"Getting-the-obstacle-attributes"},{"generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/init(from:)"],"title":"Initializers","anchor":"Initializers"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibeobstacle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nvdirectionkit\/nvibeobstacle"]}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/Se","doc:\/\/com.nvibe.NVDirectionKit\/SE","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH"],"type":"conformsTo","kind":"relationships"}],"seeAlsoSections":[{"generated":true,"anchor":"Global","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet"],"title":"Global"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeObstacle"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"type":"text","text":"A "},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","type":"reference","isActive":true},{"text":" object contains the id of the obstacle, the type of the obstacle, the position coordinate of the obstacle, the projection on the route of the obstacle and the url photo of the obstacle.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The obstacle along a route."}],"kind":"symbol","sections":[],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","title":"NVibeIndoorLocation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeIndoorLocation"}],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The address and coordinates of a indoor location."}],"navigatorTitle":[{"kind":"identifier","text":"NVibeIndoorLocation"}]},"doc://com.nvibe.NVDirectionKit/objc(pl)NSObject":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideStreet"}],"navigatorTitle":[{"text":"SideStreet","kind":"identifier"}],"abstract":[{"text":"The side of the street.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/sidestreet","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","title":"SideStreet","type":"topic"},"doc://com.nvibe.NVDirectionKit/SH":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"title":"NVibeLocation","navigatorTitle":[{"text":"NVibeLocation","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeLocation"}],"abstract":[{"text":"The address and coordinates of a location.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"type":"topic","title":"NVDirectionKit","kind":"symbol","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.5.0","type":"text"}],"url":"\/documentation\/nvdirectionkit","role":"collection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle":{"title":"NVibeObstacle","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeObstacle","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"The obstacle along a route.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibeobstacle","navigatorTitle":[{"text":"NVibeObstacle","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle"},"doc://com.nvibe.NVDirectionKit/objc(cs)NSObject":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle/projection":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The projection of the obstacle."}],"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeobstacle\/projection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/projection","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"projection","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"]","kind":"text"}],"title":"projection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle/id":{"title":"id","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","abstract":[{"text":"The id of the obstacle.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibeobstacle\/id","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/id"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle/photo":{"title":"photo","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"photo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/photo","url":"\/documentation\/nvdirectionkit\/nvibeobstacle\/photo","abstract":[{"type":"text","text":"The url photo of the obstacle."}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.nvibe.NVDirectionKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle/init(from:)":{"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/init(from:)","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(from:)","url":"\/documentation\/nvdirectionkit\/nvibeobstacle\/init(from:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle/type":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":"The type of the obstacle.","type":"text"}],"title":"type","url":"\/documentation\/nvdirectionkit\/nvibeobstacle\/type","role":"symbol","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/SQ":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/SE":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/s7CVarArgP":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle/position":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":"]"}],"abstract":[{"text":"The position of the obstacle.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/position","role":"symbol","kind":"symbol","title":"position","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibeobstacle\/position"},"doc://com.nvibe.NVDirectionKit/Se":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/Se","title":"Swift.Decodable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"NVibeObstacle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NVibeObstacle"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"NVibeObstacle","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation"],"anchor":"Global","title":"Global"}],"op":"replace"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeObstacle"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/title","value":"NVibeIndoorLocation"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/fragments","value":[{"kind":"identifier","text":"NVibeIndoorLocation"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeIndoorLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","value":"NVibeLocation"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"text":"NVibeLocation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/navigatorTitle","value":[{"text":"NVibeLocation","kind":"identifier"}]},{"value":"NVibeObstacle","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/title"},{"value":[{"text":"NVibeObstacle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/fragments"},{"value":[{"text":"NVibeObstacle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}