{"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/10Foundation14LocalizedErrorP","doc:\/\/com.nvibe.NVDirectionKit\/s8CopyableP","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/s5ErrorP","doc:\/\/com.nvibe.NVDirectionKit\/SH","doc:\/\/com.nvibe.NVDirectionKit\/s8SendableP"],"title":"Conforms To","kind":"relationships"}],"seeAlsoSections":[{"generated":true,"title":"Route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption"],"anchor":"Route"}],"metadata":{"role":"symbol","title":"RouteError","modules":[{"name":"NVDirectionKit"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RouteError","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration","externalID":"s:14NVDirectionKit10RouteErrorO","navigatorTitle":[{"text":"RouteError","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"abstract":[{"text":"Constants that describe error related to walking route calculation.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/routeerror"]}],"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RouteError","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","topicSections":[{"title":"Getting the walking route error status","anchor":"Getting-the-walking-route-error-status","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/noConnection","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/noRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/invalidToken","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/missingToken","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/maximumRequestReached","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/unknow"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/Equatable-Implementations","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/Error-Implementations","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/LocalizedError-Implementations"]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError/invalidToken":{"url":"\/documentation\/nvdirectionkit\/routeerror\/invalidtoken","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidToken"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"NVibeAPIAccessToken"},{"text":" is invalid.","type":"text"}],"title":"RouteError.invalidToken","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/invalidToken"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError/LocalizedError-Implementations":{"title":"LocalizedError Implementations","type":"topic","abstract":[],"url":"\/documentation\/nvdirectionkit\/routeerror\/localizederror-implementations","role":"collectionGroup","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/LocalizedError-Implementations","kind":"article"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError/noConnection":{"url":"\/documentation\/nvdirectionkit\/routeerror\/noconnection","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noConnection"}],"abstract":[{"text":"The user has not network capabilities.","type":"text"}],"title":"RouteError.noConnection","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/noConnection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption":{"url":"\/documentation\/nvdirectionkit\/nviberouteoption","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","navigatorTitle":[{"kind":"identifier","text":"NVibeRouteOption"}],"title":"NVibeRouteOption","abstract":[{"text":"The option for walking route.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeRouteOption","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError/maximumRequestReached":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maximumRequestReached"}],"title":"RouteError.maximumRequestReached","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/maximumRequestReached","abstract":[{"type":"text","text":"The maximum quota of request with the specified "},{"code":"NVibeAPIAccessToken","type":"codeVoice"},{"type":"text","text":"has reached."}],"type":"topic","url":"\/documentation\/nvdirectionkit\/routeerror\/maximumrequestreached","kind":"symbol","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg":{"navigatorTitle":[{"kind":"identifier","text":"NVibeLeg"}],"type":"topic","kind":"symbol","title":"NVibeLeg","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeLeg","kind":"identifier"}],"url":"\/documentation\/nvdirectionkit\/nvibeleg","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","abstract":[{"type":"text","text":"The walking leg inside walking route."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver":{"url":"\/documentation\/nvdirectionkit\/nvibemaneuver","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeManeuver","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeManeuver"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","kind":"symbol","abstract":[{"type":"text","text":"The maneuver of the walking step."}],"title":"NVibeManeuver","role":"symbol"},"doc://com.nvibe.NVDirectionKit/10Foundation14LocalizedErrorP":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError/noRoute":{"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/noRoute","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noRoute"}],"title":"RouteError.noRoute","url":"\/documentation\/nvdirectionkit\/routeerror\/noroute","abstract":[{"type":"text","text":"No walking route available with the specified parameters."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RouteError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RouteError"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/routeerror","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError","title":"RouteError","abstract":[{"text":"Constants that describe error related to walking route calculation.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/SH":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/s8CopyableP":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","type":"topic","url":"\/documentation\/nvdirectionkit\/routeerror\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/Equatable-Implementations","kind":"article"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError/unknow":{"abstract":[{"type":"text","text":"An unknow problem has occurred."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/unknow","title":"RouteError.unknow","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/nvdirectionkit\/routeerror\/unknow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknow","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError/Error-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/Error-Implementations","title":"Error Implementations","url":"\/documentation\/nvdirectionkit\/routeerror\/error-implementations","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuverDetail":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeManeuverDetail","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeManeuverDetail"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuverdetail","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","title":"NVibeManeuverDetail","abstract":[{"text":"The detail inside maneuver.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/s5ErrorP":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"navigatorTitle":[{"text":"NVibeRoute","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NVibeRoute","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeRoute"}],"url":"\/documentation\/nvdirectionkit\/nviberoute","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","abstract":[{"type":"text","text":"The walking route received when requesting walking route."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"type":"topic","title":"NVDirectionKit","kind":"symbol","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.5.0","type":"text"}],"url":"\/documentation\/nvdirectionkit","role":"collection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"type":"topic","kind":"symbol","title":"NVibeStep","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeStep","kind":"identifier"}],"url":"\/documentation\/nvdirectionkit\/nvibestep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","abstract":[{"type":"text","text":"The walking step inside walking leg."}]},"doc://com.nvibe.NVDirectionKit/s8SendableP":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError/missingToken":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"missingToken","kind":"identifier"}],"title":"RouteError.missingToken","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError\/missingToken","abstract":[{"type":"text","text":"The "},{"code":"NVibeAPIAccessToken","type":"codeVoice"},{"type":"text","text":" is missing."}],"type":"topic","url":"\/documentation\/nvdirectionkit\/routeerror\/missingtoken","kind":"symbol","role":"symbol"},"doc://com.nvibe.NVDirectionKit/SQ":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"NVibeRouteOption","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/fragments","op":"replace","value":[{"kind":"identifier","text":"NVibeRouteOption"}]},{"value":[{"text":"NVibeRouteOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/navigatorTitle"},{"value":"NVibeLeg","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/title"},{"value":[{"kind":"identifier","text":"NVibeLeg"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/fragments"},{"op":"replace","value":[{"text":"NVibeLeg","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/title","value":"NVibeManeuver","op":"replace"},{"op":"replace","value":[{"text":"NVibeManeuver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/fragments"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/navigatorTitle","value":[{"text":"NVibeManeuver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/title","value":"NVibeManeuverDetail","op":"replace"},{"value":[{"kind":"identifier","text":"NVibeManeuverDetail"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/fragments"},{"value":[{"text":"NVibeManeuverDetail","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/navigatorTitle","op":"replace"},{"value":"NVibeRoute","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments","value":[{"text":"NVibeRoute","kind":"identifier"}]},{"value":[{"text":"NVibeRoute","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","value":"NVibeStep"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments","value":[{"text":"NVibeStep","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"NVibeStep","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/navigatorTitle"}]}]}