{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can calculate multimodal route between two locations and set different parameter based on your need."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute"},{"type":"text","text":" contains one or more "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep"},{"type":"text","text":". Each "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep"},{"type":"text","text":" refers to a walking step or transit step."}]},{"style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The walking route for walking step are not directly available. It contains only the start location and the end location of the walking step. To get the route with instruction, see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute"},{"type":"text","text":"."}]}],"type":"aside","name":"Important"},{"anchor":"Calculate-a-multimodal-route","level":2,"type":"heading","text":"Calculate a multimodal route"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To calculate multimodal route, you need to use the method "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getMultimodalRoute(from:to:includeFullWalking:completion:)"},{"type":"text","text":" with a start and end "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation"},{"type":"text","text":". The first multimodal route will always be a full walking route if "},{"type":"codeVoice","code":"includeFullWalking"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["import NVDirectionKit","import CoreLocation","","class MyClass: UIViewController {","","    override func viewDidLoad() {","        let origin = CLLocationCoordinate2D(latitude: 48.85869580049223, longitude: 2.373062553499055)","        let destination = CLLocationCoordinate2D(latitude: 48.861554779024814, longitude: 2.3608910965668053)","        ","        NVDirection.shared.getMultimodalRoute(from: NVibeLocation(address: \"Pépinière 27\", position: origin), to: NVibeLocation(address: \"13 Rue Charlot\", position: destination)) { (multimodalRoutes, error) in","            guard result != nil, error == nil else {","                \/\/You will receive an error if the route calculation fails. More detail about the error in the error object.","                return","            }","            \/\/You receive the list of multimodal route here.","            for multimodalRoute in multimodalRoutes {","                for multimodalStep in multimodalRoute.steps {","                    if multimodalStep.isWalkingStep() {","                        \/\/You can calculate a walking route for the walking step here.","                        NVDirection.shared.getNavigationRoute(from: multimodalStep.startAddress, to: multimodalStep.endAddress) { (result, error) in","                            guard result != nil, error == nil else {","                                \/\/You will receive an error if the route calculation fails. More detail about the error in the error object.","                                return","                            }","                            \/\/You receive the calculated route here and additional data.","                            result.route \/\/NVibeRoute","                            result.startingDirection \/\/CLLocationDirection","                            result.solutionFound \/\/Bool","                        }","                    } else if multimodalStep.isTransitStep(), let information = multimodalStep.information.getTransitInformation() {","                        \/\/You have all the data needed about the transit to take.","                        print(\"Take the \\(information.type) \\(information.line) direction \\(information.headsign) from \\(information.departureStop.address) to \\(information.arrivalStop.address)\")","                    }","                }","            }","        }","    }","}"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvdirectionkit\/getmultimodalroute"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvdirectionkit\/getmultimodalroute"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Retrieve a multimodal route including transit between two locations."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Getting multimodal route","role":"article","modules":[{"name":"NVDirectionKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"],"generated":true}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"role":"symbol","title":"NVibeMultimodalStep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalStep"}],"abstract":[{"type":"text","text":"The multimodal step inside multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalStep"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"role":"symbol","title":"NVibeLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeLocation"}],"abstract":[{"type":"text","text":"The address and coordinates of a location."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeLocation"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getMultimodalRoute(from:to:includeFullWalking:completion:)":{"role":"symbol","title":"getMultimodalRoute(from:to:includeFullWalking:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMultimodalRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeFullWalking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"NVibeMultimodalRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"MultimodalError","preciseIdentifier":"s:14NVDirectionKit15MultimodalErrorO"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a multimodal route from completion handler."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getMultimodalRoute(from:to:includeFullWalking:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getmultimodalroute(from:to:includefullwalking:completion:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/GetRoute":{"role":"article","title":"Getting walking route","abstract":[{"type":"text","text":"Retrieve a walking route between two locations."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/getroute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"role":"symbol","title":"NVDirection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVDirection"}],"url":"\/documentation\/nvdirectionkit\/nvdirection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/GetStarted":{"role":"article","title":"Get started","abstract":[{"type":"text","text":"Configure your app to be able to use the framework."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/getstarted"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute":{"role":"symbol","title":"NVibeMultimodalRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalRoute"}],"abstract":[{"type":"text","text":"The multimodal route received when requesting multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalRoute"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","title":"NVDirectionKit","abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title","value":"NVibeMultimodalStep"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalStep"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","value":"NVibeLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"kind":"identifier","text":"NVibeLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title","value":"NVDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments","value":[{"kind":"identifier","text":"NVDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/title","value":"NVibeMultimodalRoute"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalRoute"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}