{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use NVDirectionKit, some requirements are needed."}]},{"anchor":"Dependency","level":2,"type":"heading","text":"Dependency"},{"type":"paragraph","inlineContent":[{"type":"text","text":"NVDirectionKit is available from Cocoapods. Add it to your "},{"type":"codeVoice","code":"podfile"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"ruby","code":["platform :ios, '13.0'","","target 'TargetNameForYourApp' do","    use_frameworks!","","    pod 'NVDirectionKit', '~> 0.5.0'","end"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Don’t forget to install your pod by running:"}]},{"type":"codeListing","syntax":"ruby","code":["pod install --repo-update"]},{"anchor":"Token","level":2,"type":"heading","text":"Token"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You need a token with the key "},{"type":"codeVoice","code":"NVibeAPIAccessToken"},{"type":"text","text":" to receive route from the framework. You can add it in your "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":null,"code":["<key>NVibeAPIAccessToken<\/key>","<string>YourToken<\/string>"]},{"anchor":"Http-request-permission","level":2,"type":"heading","text":"Http request permission"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use NVDirectionKit, you need also a temporary permission to allow http request, this will change later. You can add it in your "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":null,"code":["<key>NSAppTransportSecurity<\/key>","<dict>","    <key>NSAllowsArbitraryLoads<\/key>","    <true\/>","<\/dict>"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvdirectionkit\/getstarted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvdirectionkit\/getstarted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configure your app to be able to use the framework."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Get started","role":"article","modules":[{"name":"NVDirectionKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"],"generated":true}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","title":"NVDirectionKit","abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/GetRoute":{"role":"article","title":"Getting walking route","abstract":[{"type":"text","text":"Retrieve a walking route between two locations."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/getroute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/GetMultimodalRoute":{"role":"article","title":"Getting multimodal route","abstract":[{"type":"text","text":"Retrieve a multimodal route including transit between two locations."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/getmultimodalroute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"role":"symbol","title":"NVDirection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVDirection"}],"url":"\/documentation\/nvdirectionkit\/nvdirection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"],"generated":true}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title","value":"NVDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments","value":[{"kind":"identifier","text":"NVDirection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}