{"seeAlsoSections":[{"title":"MultimodalRoute","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimodalError"}],"title":"MultimodalError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:14NVDirectionKit15MultimodalErrorO","modules":[{"name":"NVDirectionKit"}],"navigatorTitle":[{"kind":"identifier","text":"MultimodalError"}]},"abstract":[{"type":"text","text":"Constants that describe error related to multimodal route calculation."}],"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/10Foundation14LocalizedErrorP","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/s5ErrorP","doc:\/\/com.nvibe.NVDirectionKit\/SH","doc:\/\/com.nvibe.NVDirectionKit\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"topicSections":[{"title":"Getting the multimodal route error status","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/noConnection","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/noMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/outOfScope","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/multipleRegion","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/invalidToken","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/missingToken","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/maximumRequestReached","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/unknow"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/Equatable-Implementations","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/Error-Implementations","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/LocalizedError-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/multimodalerror"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimodalError"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.nvibe.NVDirectionKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s8SendableP"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","title":"NVDirectionKit","abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError/multipleRegion":{"role":"symbol","title":"MultimodalError.multipleRegion","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipleRegion"}],"abstract":[{"type":"text","text":"No multimodal route available between the starting area and ending area."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/multipleRegion","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror\/multipleregion"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation":{"role":"symbol","title":"NVibeMultimodalStepInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalStepInformation"}],"abstract":[{"type":"text","text":"The information describing a multimodal step."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalStepInformation"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"role":"symbol","title":"NVibeMultimodalStep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalStep"}],"abstract":[{"type":"text","text":"The multimodal step inside multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalStep"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror\/error-implementations"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError/invalidToken":{"role":"symbol","title":"MultimodalError.invalidToken","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidToken"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"NVibeAPIAccessToken"},{"type":"text","text":" is invalid."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/invalidToken","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror\/invalidtoken"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError/unknow":{"role":"symbol","title":"MultimodalError.unknow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknow"}],"abstract":[{"type":"text","text":"An unknow problem has occurred."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/unknow","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror\/unknow"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError/noMultimodalRoute":{"role":"symbol","title":"MultimodalError.noMultimodalRoute","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noMultimodalRoute"}],"abstract":[{"type":"text","text":"No multimodal route available with the specified parameters."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/noMultimodalRoute","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror\/nomultimodalroute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError/outOfScope":{"role":"symbol","title":"MultimodalError.outOfScope","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"outOfScope"}],"abstract":[{"type":"text","text":"No multimodal route available within this area."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/outOfScope","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror\/outofscope"},"doc://com.nvibe.NVDirectionKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation":{"role":"symbol","title":"NVibeWalkingInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeWalkingInformation"}],"abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation"},"doc://com.nvibe.NVDirectionKit/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s5ErrorP"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror\/localizederror-implementations"},"doc://com.nvibe.NVDirectionKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError/missingToken":{"role":"symbol","title":"MultimodalError.missingToken","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingToken"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"NVibeAPIAccessToken"},{"type":"text","text":" is missing."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/missingToken","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror\/missingtoken"},"doc://com.nvibe.NVDirectionKit/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/10Foundation14LocalizedErrorP"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError":{"role":"symbol","title":"MultimodalError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimodalError"}],"abstract":[{"type":"text","text":"Constants that describe error related to multimodal route calculation."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultimodalError"}],"url":"\/documentation\/nvdirectionkit\/multimodalerror"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror\/equatable-implementations"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError/noConnection":{"role":"symbol","title":"MultimodalError.noConnection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noConnection"}],"abstract":[{"type":"text","text":"The user has not network capabilities."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/noConnection","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror\/noconnection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute":{"role":"symbol","title":"NVibeMultimodalRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalRoute"}],"abstract":[{"type":"text","text":"The multimodal route received when requesting multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalRoute"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError/maximumRequestReached":{"role":"symbol","title":"MultimodalError.maximumRequestReached","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumRequestReached"}],"abstract":[{"type":"text","text":"The maximum quota of request with the specified "},{"type":"codeVoice","code":"NVibeAPIAccessToken"},{"type":"text","text":"has reached."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError\/maximumRequestReached","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror\/maximumrequestreached"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation":{"role":"symbol","title":"NVibeTransitInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeTransitInformation"}],"abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitInformation"}],"url":"\/documentation\/nvdirectionkit\/nvibetransitinformation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/title","value":"NVibeMultimodalStepInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalStepInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title","value":"NVibeMultimodalStep"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalStep"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/title","value":"NVibeWalkingInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/fragments","value":[{"kind":"identifier","text":"NVibeWalkingInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/title","value":"NVibeMultimodalRoute"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/title","value":"NVibeTransitInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/fragments","value":[{"kind":"identifier","text":"NVibeTransitInformation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}