{"seeAlsoSections":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"title":"NVDirection","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@NVDirectionKit@objc(cs)NVDirection","modules":[{"name":"NVDirectionKit"}],"navigatorTitle":[{"kind":"identifier","text":"NVDirection"}]},"abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}],"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"topicSections":[{"title":"Accessing services","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/shared"]},{"title":"Requesting walking route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:completion:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withAlternativePolyline:completion:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getCustomNavigationRoute(from:to:with:language:completion:)"]},{"title":"Requesting multimodal route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getMultimodalRoute(from:to:includeFullWalking:completion:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNextDeparture(from:count:completion:)"]},{"title":"Cancelling request","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/cancelRoute()"]}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvdirection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvdirectionkit\/nvdirection"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"},{"type":"text","text":" object is used to request route."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information, see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute"},{"type":"text","text":"."}]}]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","title":"NVDirectionKit","abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getCustomNavigationRoute(from:to:with:language:completion:)":{"role":"symbol","title":"getCustomNavigationRoute(from:to:with:language:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCustomNavigationRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"kind":"text","text":", startingDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":")?, "},{"kind":"typeIdentifier","text":"RouteError","preciseIdentifier":"s:14NVDirectionKit10RouteErrorO"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a custom walking route from a set of coordinates."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getCustomNavigationRoute(from:to:with:language:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getcustomnavigationroute(from:to:with:language:completion:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getNextDeparture(from:count:completion:)":{"role":"symbol","title":"getNextDeparture(from:count:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getNextDeparture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns the next departure for the given transit."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNextDeparture(from:count:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getnextdeparture(from:count:completion:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/GetStarted":{"role":"article","title":"Get started","abstract":[{"type":"text","text":"Configure your app to be able to use the framework."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/getstarted"},"doc://com.nvibe.NVDirectionKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/cancelRoute()":{"role":"symbol","title":"cancelRoute()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelRoute"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Cancel all request."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/cancelRoute()","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/cancelroute()"},"doc://com.nvibe.NVDirectionKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVDirection","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVDirection"}],"abstract":[{"type":"text","text":"Singleton property."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/shared","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/shared"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/GetRoute":{"role":"article","title":"Getting walking route","abstract":[{"type":"text","text":"Retrieve a walking route between two locations."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/getroute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/GetMultimodalRoute":{"role":"article","title":"Getting multimodal route","abstract":[{"type":"text","text":"Retrieve a multimodal route including transit between two locations."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/getmultimodalroute"},"doc://com.nvibe.NVDirectionKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getStartingDirection(from:to:completion:)":{"role":"symbol","title":"getStartingDirection(from:to:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStartingDirection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"RouteError","preciseIdentifier":"s:14NVDirectionKit10RouteErrorO"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns the starting direction of a walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getstartingdirection(from:to:completion:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getMultimodalRoute(from:to:includeFullWalking:completion:)":{"role":"symbol","title":"getMultimodalRoute(from:to:includeFullWalking:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMultimodalRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includeFullWalking"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"NVibeMultimodalRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"MultimodalError","preciseIdentifier":"s:14NVDirectionKit15MultimodalErrorO"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a multimodal route from completion handler."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getMultimodalRoute(from:to:includeFullWalking:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getmultimodalroute(from:to:includefullwalking:completion:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/nvdirectionkit\/nvdirection\/init"},"doc://com.nvibe.NVDirectionKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"},"doc://com.nvibe.NVDirectionKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH"},"doc://com.nvibe.NVDirectionKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"role":"symbol","title":"NVDirection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVDirection"}],"url":"\/documentation\/nvdirectionkit\/nvdirection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withAlternativePolyline:completion:)":{"role":"symbol","title":"getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withAlternativePolyline:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getNavigationRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sideStreet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SideStreet","preciseIdentifier":"s:14NVDirectionKit10SideStreetO"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withObstacle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forbiddenObstacles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"withAlternativePolyline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"kind":"text","text":", startingDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":", solutionFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")?, "},{"kind":"typeIdentifier","text":"RouteError","preciseIdentifier":"s:14NVDirectionKit10RouteErrorO"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withAlternativePolyline:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getnavigationroute(from:to:sidestreet:language:withobstacle:forbiddenobstacles:withalternativepolyline:completion:)"},"doc://com.nvibe.NVDirectionKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"NVDirection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NVDirection"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"NVDirection"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title","value":"NVDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments","value":[{"kind":"identifier","text":"NVDirection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}