{"seeAlsoSections":[{"title":"Route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRoute"}],"title":"NVibeRoute","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@NVDirectionKit@objc(cs)NVibeRoute","modules":[{"name":"NVDirectionKit"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeRoute"}]},"abstract":[{"type":"text","text":"The walking route received when requesting walking route."}],"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"topicSections":[{"title":"Getting the walking route attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/startAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/endAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/distance","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/duration","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/legs","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/geometry","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/alternativeGeometry","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/coordinates","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/option"]},{"title":"Getting the GPX from the walking route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/toGPX(speed:)"]}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nviberoute"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvdirectionkit\/nviberoute"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRoute"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/distance":{"role":"symbol","title":"distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The distance in meter of the walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/distance","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/distance"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/coordinates":{"role":"symbol","title":"coordinates","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The list of coordinates representing the walking route (decoded geometry)."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/coordinates","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/coordinates"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/option":{"role":"symbol","title":"option","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRouteOption","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRouteOption"}],"abstract":[{"type":"text","text":"The option of the walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/option","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/option"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/endAddress":{"role":"symbol","title":"endAddress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"}],"abstract":[{"type":"text","text":"The end location of the walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/endAddress","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/endaddress"},"doc://com.nvibe.NVDirectionKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"role":"symbol","title":"NVibeRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRoute"}],"abstract":[{"type":"text","text":"The walking route received when requesting walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRoute"}],"url":"\/documentation\/nvdirectionkit\/nviberoute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"role":"symbol","title":"NVibeStep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeStep"}],"abstract":[{"type":"text","text":"The walking step inside walking leg."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"url":"\/documentation\/nvdirectionkit\/nvibestep"},"doc://com.nvibe.NVDirectionKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/duration":{"role":"symbol","title":"duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The duration in second of the walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/duration","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/duration"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg":{"role":"symbol","title":"NVibeLeg","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeLeg"}],"abstract":[{"type":"text","text":"The walking leg inside walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeLeg"}],"url":"\/documentation\/nvdirectionkit\/nvibeleg"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/toGPX(speed:)":{"role":"symbol","title":"toGPX(speed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toGPX"},{"kind":"text","text":"("},{"kind":"externalParam","text":"speed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Returns a "},{"type":"codeVoice","code":"String"},{"type":"text","text":" value representing the GPX of the walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/toGPX(speed:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/togpx(speed:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","title":"NVDirectionKit","abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit"},"doc://com.nvibe.NVDirectionKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"},"doc://com.nvibe.NVDirectionKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ"},"doc://com.nvibe.NVDirectionKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver":{"role":"symbol","title":"NVibeManeuver","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeManeuver"}],"abstract":[{"type":"text","text":"The maneuver of the walking step."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeManeuver"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/alternativeGeometry":{"role":"symbol","title":"alternativeGeometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alternativeGeometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The alternative geometry (encoded with an accuracy of 6) of the walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/alternativeGeometry","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/alternativegeometry"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/startAddress":{"role":"symbol","title":"startAddress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"}],"abstract":[{"type":"text","text":"The start location of the walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/startAddress","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/startaddress"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError":{"role":"symbol","title":"RouteError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteError"}],"abstract":[{"type":"text","text":"Constants that describe error related to walking route calculation."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RouteError"}],"url":"\/documentation\/nvdirectionkit\/routeerror"},"doc://com.nvibe.NVDirectionKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/geometry":{"role":"symbol","title":"geometry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The geometry (encoded with an accuracy of 6) of the walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/geometry","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/geometry"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuverDetail":{"role":"symbol","title":"NVibeManeuverDetail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeManeuverDetail"}],"abstract":[{"type":"text","text":"The detail inside maneuver."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeManeuverDetail"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuverdetail"},"doc://com.nvibe.NVDirectionKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/legs":{"role":"symbol","title":"legs","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"legs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NVibeLeg","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLeg"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The list of leg of the walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/legs","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/legs"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption":{"role":"symbol","title":"NVibeRouteOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteOption"}],"abstract":[{"type":"text","text":"The option for walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRouteOption"}],"url":"\/documentation\/nvdirectionkit\/nviberouteoption"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"NVibeRoute"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NVibeRoute"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeRoute"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRoute"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title","value":"NVibeRoute"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments","value":[{"kind":"identifier","text":"NVibeRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","value":"NVibeStep"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments","value":[{"kind":"identifier","text":"NVibeStep"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/title","value":"NVibeLeg"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/fragments","value":[{"kind":"identifier","text":"NVibeLeg"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/title","value":"NVibeManeuver"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/fragments","value":[{"kind":"identifier","text":"NVibeManeuver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/title","value":"NVibeManeuverDetail"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/fragments","value":[{"kind":"identifier","text":"NVibeManeuverDetail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/title","value":"NVibeRouteOption"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/fragments","value":[{"kind":"identifier","text":"NVibeRouteOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}