{"seeAlsoSections":[{"title":"Global","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideStreet"}],"title":"SideStreet","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:14NVDirectionKit10SideStreetO","modules":[{"name":"NVDirectionKit"}],"navigatorTitle":[{"kind":"identifier","text":"SideStreet"}]},"abstract":[{"type":"text","text":"The side of the street."}],"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH","doc:\/\/com.nvibe.NVDirectionKit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet\/LEFT","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet\/RIGHT"]},{"title":"Initializers","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet\/Equatable-Implementations","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/sidestreet"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideStreet"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet/LEFT":{"role":"symbol","title":"SideStreet.LEFT","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"LEFT"}],"abstract":[{"type":"text","text":"The left side of the street."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet\/LEFT","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/sidestreet\/left"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle":{"role":"symbol","title":"NVibeObstacle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeObstacle"}],"abstract":[{"type":"text","text":"The obstacle along a route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeObstacle"}],"url":"\/documentation\/nvdirectionkit\/nvibeobstacle"},"doc://com.nvibe.NVDirectionKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet":{"role":"symbol","title":"SideStreet","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideStreet"}],"abstract":[{"type":"text","text":"The side of the street."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SideStreet"}],"url":"\/documentation\/nvdirectionkit\/sidestreet"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation":{"role":"symbol","title":"NVibeIndoorLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeIndoorLocation"}],"abstract":[{"type":"text","text":"The address and coordinates of a indoor location."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeIndoorLocation"}],"url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"role":"symbol","title":"NVibeLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeLocation"}],"abstract":[{"type":"text","text":"The address and coordinates of a location."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeLocation"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/sidestreet\/equatable-implementations"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","title":"NVDirectionKit","abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit"},"doc://com.nvibe.NVDirectionKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/sidestreet\/init(rawvalue:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet/RIGHT":{"role":"symbol","title":"SideStreet.RIGHT","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"RIGHT"}],"abstract":[{"type":"text","text":"The right side of the street."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet\/RIGHT","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/sidestreet\/right"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/sidestreet\/rawrepresentable-implementations"},"doc://com.nvibe.NVDirectionKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/title","value":"NVibeObstacle"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/fragments","value":[{"kind":"identifier","text":"NVibeObstacle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/title","value":"NVibeIndoorLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/fragments","value":[{"kind":"identifier","text":"NVibeIndoorLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","value":"NVibeLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"kind":"identifier","text":"NVibeLocation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}