{"metadata":{"externalID":"s:14NVDirectionKit0A0C18getMultimodalRoute4from2to15onlyFullWalking04withiJ11Alternative5avoid10completionyAA13NVibeLocationC_ALS2bSayAA0O18TransitInformationC4ModeOGySayAA0odE0CGSg_AA0D5ErrorOSgtctF","modules":[{"name":"NVDirectionKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getMultimodalRoute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onlyFullWalking"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"withFullWalkingAlternative","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"text":"NVibeTransitInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"s:14NVDirectionKit23NVibeTransitInformationC4ModeO"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (["},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute","kind":"typeIdentifier","text":"NVibeMultimodalRoute"},{"text":"]?, ","kind":"text"},{"preciseIdentifier":"s:14NVDirectionKit15MultimodalErrorO","text":"MultimodalError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol","title":"getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:completion:)","symbolKind":"method"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvdirection\/getmultimodalroute(from:to:onlyfullwalking:withfullwalkingalternative:avoid:completion:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"generated":true,"title":"Requesting multimodal route","anchor":"Requesting-multimodal-route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNextDeparture(from:count:completion:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNextDeparture(from:count:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getMultimodalRoute","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"startLocation","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"text":"to","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"endLocation"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"},{"kind":"text","text":", "},{"text":"onlyFullWalking","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"withFullWalkingAlternative","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"avoid","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","kind":"typeIdentifier","text":"NVibeTransitInformation"},{"kind":"text","text":"."},{"text":"Mode","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/Mode","kind":"typeIdentifier","preciseIdentifier":"s:14NVDirectionKit23NVibeTransitInformationC4ModeO"},{"text":"] = [], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (["},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","text":"NVibeMultimodalRoute","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError","kind":"typeIdentifier","text":"MultimodalError","preciseIdentifier":"s:14NVDirectionKit15MultimodalErrorO"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"startLocation","content":[{"type":"paragraph","inlineContent":[{"text":"The departure of the route.","type":"text"}]}]},{"name":"endLocation","content":[{"type":"paragraph","inlineContent":[{"text":"The arrival of the route.","type":"text"}]}]},{"name":"onlyFullWalking","content":[{"inlineContent":[{"type":"text","text":"Set "},{"code":"true","type":"codeVoice"},{"text":" to get only full walking route without transit. Set ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" to additionnaly include route with transit. The default value of this property is ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Set ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" to get full walking route alternative. Set "},{"type":"codeVoice","code":"false"},{"text":" to get only one full walking route. The default value of this property is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}]}],"name":"withFullWalkingAlternative"},{"name":"avoid","content":[{"type":"paragraph","inlineContent":[{"text":"The list of type of transit to avoid.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A closure to execute after the request is completed. This closure takes a list of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute"},{"text":" and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError"},{"type":"text","text":" parameters. If the request was successfull, it returns the list otherwise the error."}]}],"name":"completion"}]}],"abstract":[{"text":"Returns multimodal routes from completion handler.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:completion:)"},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getMultimodalRoute","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onlyFullWalking","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withFullWalkingAlternative"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"text":"NVibeTransitInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"s:14NVDirectionKit23NVibeTransitInformationC4ModeO"},{"kind":"text","text":"]) "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> [","kind":"text"},{"text":"NVibeMultimodalRoute","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Returns multimodal routes asynchronously."}],"url":"\/documentation\/nvdirectionkit\/nvdirection\/getmultimodalroute(from:to:onlyfullwalking:withfullwalkingalternative:avoid:)","title":"getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getNextDeparture(from:count:completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNextDeparture(from:count:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getNextDeparture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeTransitInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation"},{"kind":"text","text":", "},{"text":"count","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Returns the next departure for the given transit from completion handler."}],"url":"\/documentation\/nvdirectionkit\/nvdirection\/getnextdeparture(from:count:completion:)","title":"getNextDeparture(from:count:completion:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation":{"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation","title":"NVibeTransitInformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeTransitInformation"}],"abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitInformation"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"kind":"symbol","title":"NVDirection","navigatorTitle":[{"text":"NVDirection","kind":"identifier"}],"type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVDirection","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/Mode":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/Mode","type":"topic","abstract":[{"type":"text","text":"Constants that describe the mode of the transit multimodal step."}],"url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/mode","navigatorTitle":[{"text":"Mode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"NVibeTransitInformation.Mode"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getMultimodalRoute"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onlyFullWalking"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withFullWalkingAlternative"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"avoid"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation","text":"NVibeTransitInformation"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14NVDirectionKit23NVibeTransitInformationC4ModeO","text":"Mode","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"text":": ([","kind":"text"},{"kind":"typeIdentifier","text":"NVibeMultimodalRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalRoute"},{"text":"]?, ","kind":"text"},{"preciseIdentifier":"s:14NVDirectionKit15MultimodalErrorO","text":"MultimodalError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:completion:)","kind":"symbol","title":"getMultimodalRoute(from:to:onlyFullWalking:withFullWalkingAlternative:avoid:completion:)","url":"\/documentation\/nvdirectionkit\/nvdirection\/getmultimodalroute(from:to:onlyfullwalking:withfullwalkingalternative:avoid:completion:)","abstract":[{"type":"text","text":"Returns multimodal routes from completion handler."}],"type":"topic","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeMultimodalRoute"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","kind":"symbol","navigatorTitle":[{"text":"NVibeMultimodalRoute","kind":"identifier"}],"title":"NVibeMultimodalRoute","url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute","abstract":[{"type":"text","text":"The multimodal route received when requesting multimodal route."}],"type":"topic","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"abstract":[{"text":"The address and coordinates of a location.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","url":"\/documentation\/nvdirectionkit\/nvibelocation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeLocation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeLocation"}],"type":"topic","kind":"symbol","title":"NVibeLocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError":{"type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimodalError","kind":"identifier"}],"title":"MultimodalError","abstract":[{"text":"Constants that describe error related to multimodal route calculation.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError","navigatorTitle":[{"text":"MultimodalError","kind":"identifier"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getNextDeparture(from:count:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getNextDeparture"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation","text":"NVibeTransitInformation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"count","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNextDeparture(from:count:)","kind":"symbol","title":"getNextDeparture(from:count:)","url":"\/documentation\/nvdirectionkit\/nvdirection\/getnextdeparture(from:count:)","abstract":[{"type":"text","text":"Returns the next departure for the given transit asynchronously."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"NVibeTransitInformation","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/fragments","value":[{"kind":"identifier","text":"NVibeTransitInformation"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NVibeTransitInformation"}]},{"value":"NVDirection","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments","value":[{"text":"NVDirection","kind":"identifier"}],"op":"replace"},{"value":[{"text":"NVDirection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/title","value":"NVibeMultimodalRoute","op":"replace"},{"value":[{"text":"NVibeMultimodalRoute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/navigatorTitle","value":[{"text":"NVibeMultimodalRoute","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","value":"NVibeLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"text":"NVibeLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeLocation"}]}]}]}