{"seeAlsoSections":[{"generated":true,"title":"Requesting walking route","anchor":"Requesting-walking-route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:completion:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRouteWithoutCrossing(from:to:option:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:option:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getCustomNavigationRoute(from:to:with:language:completion:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getCustomNavigationRoute(from:to:with:language:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Method","role":"symbol","externalID":"s:14NVDirectionKit0A0C18getNavigationRoute4from2to10sideStreet8language12withObstacle18forbiddenObstacles0K16InformationPoint0K19AlternativePolyline10completionyAA13NVibeLocationC_AoA04SideI0OSgSSSbSaySSGS2byAA0tE0C5route_Sd17startingDirectionSb13solutionFoundtSg_AA0E5ErrorOSgtctF","symbolKind":"method","title":"getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:completion:)","modules":[{"name":"NVDirectionKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getNavigationRoute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sideStreet","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14NVDirectionKit10SideStreetO","text":"SideStreet"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withObstacle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"forbiddenObstacles","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"withInformationPoint"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"withAlternativePolyline","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((route","kind":"text"},{"kind":"text","text":": "},{"text":"NVibeRoute","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"text":", startingDirection","kind":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection"},{"text":", solutionFound","kind":"text"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"preciseIdentifier":"s:14NVDirectionKit10RouteErrorO","text":"RouteError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}]},"abstract":[{"type":"text","text":"Returns a walking route from completion handler."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getNavigationRoute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"startLocation"},{"kind":"text","text":": "},{"text":"NVibeLocation","kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":" "},{"text":"endLocation","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sideStreet"},{"text":": ","kind":"text"},{"text":"SideStreet","kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","preciseIdentifier":"s:14NVDirectionKit10SideStreetO"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"language"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"en\", ","kind":"text"},{"text":"withObstacle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"text":"forbiddenObstacles","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"withInformationPoint"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"withAlternativePolyline","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ((route","kind":"text"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","kind":"typeIdentifier","text":"NVibeRoute"},{"text":", startingDirection","kind":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","kind":"typeIdentifier","text":"CLLocationDirection"},{"text":", solutionFound","kind":"text"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")?, "},{"text":"RouteError","kind":"typeIdentifier","preciseIdentifier":"s:14NVDirectionKit10RouteErrorO","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"startLocation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The departure of the route."}]}]},{"name":"endLocation","content":[{"inlineContent":[{"type":"text","text":"The arrival of the route."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The side of the street from where the user starts."}],"type":"paragraph"}],"name":"sideStreet"},{"content":[{"inlineContent":[{"text":"The language of instruction (English (en), French (fr), Dutch (nl), Spanish (es), German (de)). The default value of this property is ","type":"text"},{"type":"codeVoice","code":"en"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"language"},{"name":"withObstacle","content":[{"inlineContent":[{"text":"Set ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" to include ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle"},{"type":"text","text":" on the route. The default value of this property is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"forbiddenObstacles","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set a list of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/id"},{"type":"text","text":" to avoid them if possible."}]}]},{"name":"withInformationPoint","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Set "},{"type":"codeVoice","code":"true"},{"text":" to include ","type":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint","type":"reference","isActive":true},{"type":"text","text":" on the route. The default value of this property is "},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":" to include an "},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/alternativeGeometry","isActive":true,"type":"reference"},{"text":" shifted on the side of the street instead of the middle of the route. The default geometry is always available with ","type":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/geometry","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"name":"withAlternativePolyline"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A closure to execute after the request is completed. This closure takes a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","type":"reference"},{"type":"text","text":", "},{"type":"codeVoice","code":"Double"},{"type":"text","text":", "},{"type":"codeVoice","code":"Bool"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError","type":"reference"},{"type":"text","text":" parameters. If the request was successfull, it returns the route, the starting direction and a boolean value that indicates whether the route is crossable otherwise the error."}]}],"name":"completion"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:completion:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvdirection\/getnavigationroute(from:to:sidestreet:language:withobstacle:forbiddenobstacles:withinformationpoint:withalternativepolyline:completion:)"]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getStartingDirection(from:to:completion:)":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:completion:)","abstract":[{"type":"text","text":"Returns the starting direction of a walking route from completion handler."}],"type":"topic","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvdirection\/getstartingdirection(from:to:completion:)","title":"getStartingDirection(from:to:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getStartingDirection","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"RouteError","preciseIdentifier":"s:14NVDirectionKit10RouteErrorO","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getNavigationRouteWithoutCrossing(from:to:option:)":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRouteWithoutCrossing(from:to:option:)","abstract":[{"type":"text","text":"Returns a walking route without crossing asynchronously using "},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvdirection\/getnavigationroutewithoutcrossing(from:to:option:)","title":"getNavigationRouteWithoutCrossing(from:to:option:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getNavigationRouteWithoutCrossing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier","text":"NVibeLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"option"},{"text":": ","kind":"text"},{"text":"NVibeRouteOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRouteOption"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> (route","kind":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute","text":"NVibeRoute"},{"kind":"text","text":", startingDirection"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","kind":"typeIdentifier","text":"CLLocationDirection"},{"kind":"text","text":")"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/geometry":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/geometry","title":"geometry","type":"topic","abstract":[{"text":"The geometry (encoded with an accuracy of 6) of the walking route.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nviberoute\/geometry","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"geometry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:)":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:)","abstract":[{"type":"text","text":"Returns a walking route asynchronously."}],"type":"topic","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvdirection\/getnavigationroute(from:to:sidestreet:language:withobstacle:forbiddenobstacles:withinformationpoint:withalternativepolyline:)","title":"getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getNavigationRoute"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sideStreet"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SideStreet","preciseIdentifier":"s:14NVDirectionKit10SideStreetO"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"language"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withObstacle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forbiddenObstacles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"text":"withInformationPoint","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withAlternativePolyline"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> (route"},{"text":": ","kind":"text"},{"text":"NVibeRoute","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"text":", startingDirection","kind":"text"},{"kind":"text","text":": "},{"text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection","kind":"typeIdentifier"},{"kind":"text","text":", solutionFound"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"abstract":[{"text":"The address and coordinates of a location.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","url":"\/documentation\/nvdirectionkit\/nvibelocation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeLocation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeLocation"}],"type":"topic","kind":"symbol","title":"NVibeLocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint":{"type":"topic","kind":"symbol","title":"NVibeInformationPoint","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeInformationPoint","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeInformationPoint"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint","abstract":[{"text":"The information point along a route.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getNavigationRoute(from:to:sideStreet:option:)":{"kind":"symbol","title":"getNavigationRoute(from:to:sideStreet:option:)","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getnavigationroute(from:to:sidestreet:option:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getNavigationRoute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sideStreet"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14NVDirectionKit10SideStreetO","text":"SideStreet","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"option","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NVibeRouteOption","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRouteOption","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> (route","kind":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"kind":"text","text":", startingDirection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"},{"text":", solutionFound","kind":"text"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:option:)","abstract":[{"type":"text","text":"Returns a walking route with crossing asynchronously using "},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","isActive":true,"type":"reference"},{"type":"text","text":"."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getCustomNavigationRoute(from:to:with:language:completion:)":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getCustomNavigationRoute(from:to:with:language:completion:)","abstract":[{"text":"Returns a custom walking route from a set of coordinates from completion handler.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvdirection\/getcustomnavigationroute(from:to:with:language:completion:)","title":"getCustomNavigationRoute(from:to:with:language:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getCustomNavigationRoute","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"},{"kind":"text","text":", "},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"language"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((route","kind":"text"},{"text":": ","kind":"text"},{"text":"NVibeRoute","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"text":", startingDirection","kind":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"preciseIdentifier":"s:14NVDirectionKit10RouteErrorO","text":"RouteError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError":{"role":"symbol","navigatorTitle":[{"text":"RouteError","kind":"identifier"}],"abstract":[{"text":"Constants that describe error related to walking route calculation.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/routeerror","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RouteError"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError","type":"topic","title":"RouteError"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"kind":"symbol","title":"NVDirection","navigatorTitle":[{"text":"NVDirection","kind":"identifier"}],"type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVDirection","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getCustomNavigationRoute(from:to:with:language:)":{"kind":"symbol","title":"getCustomNavigationRoute(from:to:with:language:)","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getcustomnavigationroute(from:to:with:language:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getCustomNavigationRoute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"language","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> (route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute","text":"NVibeRoute"},{"text":", startingDirection","kind":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getCustomNavigationRoute(from:to:with:language:)","abstract":[{"text":"Returns a custom walking route from a set of coordinates asynchronously.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle/id":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle\/id","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"id","abstract":[{"type":"text","text":"The id of the obstacle."}],"url":"\/documentation\/nvdirectionkit\/nvibeobstacle\/id"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","title":"NVibeObstacle","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeobstacle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NVibeObstacle","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeObstacle","kind":"identifier"}],"abstract":[{"type":"text","text":"The obstacle along a route."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","abstract":[{"type":"text","text":"The option for walking route."}],"type":"topic","role":"symbol","url":"\/documentation\/nvdirectionkit\/nviberouteoption","navigatorTitle":[{"text":"NVibeRouteOption","kind":"identifier"}],"title":"NVibeRouteOption","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteOption"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:completion:)":{"kind":"symbol","title":"getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:completion:)","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getnavigationroute(from:to:sidestreet:language:withobstacle:forbiddenobstacles:withinformationpoint:withalternativepolyline:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getNavigationRoute"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sideStreet","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SideStreet","kind":"typeIdentifier","preciseIdentifier":"s:14NVDirectionKit10SideStreetO"},{"kind":"text","text":"?, "},{"text":"language","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"withObstacle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forbiddenObstacles"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"withInformationPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"withAlternativePolyline","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((route","kind":"text"},{"text":": ","kind":"text"},{"text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute","kind":"typeIdentifier"},{"text":", startingDirection","kind":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CLLocationDirection","text":"CLLocationDirection","kind":"typeIdentifier"},{"text":", solutionFound","kind":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")?, ","kind":"text"},{"preciseIdentifier":"s:14NVDirectionKit10RouteErrorO","text":"RouteError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withInformationPoint:withAlternativePolyline:completion:)","abstract":[{"type":"text","text":"Returns a walking route from completion handler."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/alternativeGeometry":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/alternativeGeometry","title":"alternativeGeometry","type":"topic","abstract":[{"text":"The alternative geometry (encoded with an accuracy of 6) of the walking route.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nviberoute\/alternativegeometry","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alternativeGeometry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"abstract":[{"text":"The walking route received when requesting walking route.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRoute"}],"url":"\/documentation\/nvdirectionkit\/nviberoute","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeRoute"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","kind":"symbol","title":"NVibeRoute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getStartingDirection(from:to:)":{"kind":"symbol","title":"getStartingDirection(from:to:)","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getstartingdirection(from:to:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getStartingDirection","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":", ","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:)","abstract":[{"type":"text","text":"Returns the starting direction of a walking route asynchronously."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet":{"title":"SideStreet","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","navigatorTitle":[{"kind":"identifier","text":"SideStreet"}],"url":"\/documentation\/nvdirectionkit\/sidestreet","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The side of the street."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SideStreet","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"NVibeLocation","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title"},{"value":[{"kind":"identifier","text":"NVibeLocation"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeLocation"}]},{"value":"NVibeInformationPoint","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/title","op":"replace"},{"op":"replace","value":[{"text":"NVibeInformationPoint","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/fragments"},{"value":[{"kind":"identifier","text":"NVibeInformationPoint"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title","value":"NVDirection","op":"replace"},{"value":[{"text":"NVDirection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/navigatorTitle","value":[{"kind":"identifier","text":"NVDirection"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/title","op":"replace","value":"NVibeObstacle"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/fragments","value":[{"text":"NVibeObstacle","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NVibeObstacle"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/title","value":"NVibeRouteOption"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/fragments","value":[{"text":"NVibeRouteOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NVibeRouteOption"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title","op":"replace","value":"NVibeRoute"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments","value":[{"kind":"identifier","text":"NVibeRoute"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/navigatorTitle","value":[{"text":"NVibeRoute","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}