{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/shared"},"kind":"symbol","variants":[{"paths":["\/documentation\/nvdirectionkit\/nvdirection\/shared"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVDirection","kind":"typeIdentifier","text":"NVDirection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"}]}]}],"abstract":[{"type":"text","text":"Singleton property."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","roleHeading":"Type Property","title":"shared","role":"symbol","modules":[{"name":"NVDirectionKit"}],"externalID":"s:14NVDirectionKit0A0C6sharedACvpZ","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVDirection","text":"NVDirection"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]]},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"kind":"symbol","title":"NVDirection","navigatorTitle":[{"text":"NVDirection","kind":"identifier"}],"type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVDirection","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/shared":{"url":"\/documentation\/nvdirectionkit\/nvdirection\/shared","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVDirection","text":"NVDirection"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/shared","role":"symbol","abstract":[{"type":"text","text":"Singleton property."}],"title":"shared"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title","value":"NVDirection"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments","value":[{"kind":"identifier","text":"NVDirection"}],"op":"replace"},{"value":[{"kind":"identifier","text":"NVDirection"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}