{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCustomNavigationRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"startLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"endLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"coordinates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = \"en\", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ((route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute","text":"NVibeRoute"},{"kind":"text","text":", startingDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":")?, "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError","preciseIdentifier":"s:14NVDirectionKit10RouteErrorO","text":"RouteError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"startLocation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The departure of the route."}]}]},{"name":"endLocation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The arrival of the route."}]}]},{"name":"coordinates","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The list of coordinates to create the custom route. Need at least two coordinates."}]}]},{"name":"language","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The language of instruction (English (en), French (fr), Dutch (nl), Spanish (es), German (de)). The default value of this property is "},{"type":"codeVoice","code":"en"},{"type":"text","text":"."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure to execute after the request is completed. This closure takes a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute"},{"type":"text","text":", "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError"},{"type":"text","text":" parameters. If the request was successfull, it returns the route and the starting direction otherwise the error."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvdirection\/getcustomnavigationroute(from:to:with:language:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getCustomNavigationRoute(from:to:with:language:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns a custom walking route from a set of coordinates."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCustomNavigationRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"kind":"text","text":", startingDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":")?, "},{"kind":"typeIdentifier","text":"RouteError","preciseIdentifier":"s:14NVDirectionKit10RouteErrorO"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"getCustomNavigationRoute(from:to:with:language:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:14NVDirectionKit0A0C24getCustomNavigationRoute4from2to4with8language10completionyAA13NVibeLocationC_AKSaySo22CLLocationCoordinate2DVGSSyAA0lF0C5route_Sd17startingDirectiontSg_AA0F5ErrorOSgtctF","modules":[{"name":"NVDirectionKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]]},"seeAlsoSections":[{"title":"Requesting walking route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:completion:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withAlternativePolyline:completion:)"],"generated":true}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError":{"role":"symbol","title":"RouteError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteError"}],"abstract":[{"type":"text","text":"Constants that describe error related to walking route calculation."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RouteError"}],"url":"\/documentation\/nvdirectionkit\/routeerror"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getCustomNavigationRoute(from:to:with:language:completion:)":{"role":"symbol","title":"getCustomNavigationRoute(from:to:with:language:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCustomNavigationRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"kind":"text","text":", startingDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":")?, "},{"kind":"typeIdentifier","text":"RouteError","preciseIdentifier":"s:14NVDirectionKit10RouteErrorO"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a custom walking route from a set of coordinates."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getCustomNavigationRoute(from:to:with:language:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getcustomnavigationroute(from:to:with:language:completion:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getStartingDirection(from:to:completion:)":{"role":"symbol","title":"getStartingDirection(from:to:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStartingDirection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"RouteError","preciseIdentifier":"s:14NVDirectionKit10RouteErrorO"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns the starting direction of a walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getStartingDirection(from:to:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getstartingdirection(from:to:completion:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withAlternativePolyline:completion:)":{"role":"symbol","title":"getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withAlternativePolyline:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getNavigationRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sideStreet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SideStreet","preciseIdentifier":"s:14NVDirectionKit10SideStreetO"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withObstacle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forbiddenObstacles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"withAlternativePolyline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((route"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NVibeRoute","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRoute"},{"kind":"text","text":", startingDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationDirection","preciseIdentifier":"c:@T@CLLocationDirection"},{"kind":"text","text":", solutionFound"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")?, "},{"kind":"typeIdentifier","text":"RouteError","preciseIdentifier":"s:14NVDirectionKit10RouteErrorO"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection\/getNavigationRoute(from:to:sideStreet:language:withObstacle:forbiddenObstacles:withAlternativePolyline:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirection\/getnavigationroute(from:to:sidestreet:language:withobstacle:forbiddenobstacles:withalternativepolyline:completion:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"role":"symbol","title":"NVDirection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVDirection"}],"url":"\/documentation\/nvdirectionkit\/nvdirection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","title":"NVDirectionKit","abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"role":"symbol","title":"NVibeRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRoute"}],"abstract":[{"type":"text","text":"The walking route received when requesting walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRoute"}],"url":"\/documentation\/nvdirectionkit\/nviberoute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"role":"symbol","title":"NVibeLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeLocation"}],"abstract":[{"type":"text","text":"The address and coordinates of a location."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeLocation"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title","value":"NVDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments","value":[{"kind":"identifier","text":"NVDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title","value":"NVibeRoute"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments","value":[{"kind":"identifier","text":"NVibeRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","value":"NVibeLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"kind":"identifier","text":"NVibeLocation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}