{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"address","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The address of the location."}],"type":"paragraph"}],"name":"address"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The position coordinate of the location."}]}],"name":"position"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibelocation\/init(address:position:)"]}],"metadata":{"role":"symbol","symbolKind":"init","roleHeading":"Initializer","title":"init(address:position:)","externalID":"s:14NVDirectionKit13NVibeLocationC7address8positionACSS_So22CLLocationCoordinate2DVtcfc","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"address","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":")","kind":"text"}],"modules":[{"name":"NVDirectionKit"}]},"kind":"symbol","abstract":[{"text":"Creates a location object with the specified address and position values.","type":"text"}],"seeAlsoSections":[{"anchor":"Creating-a-location","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(address:position:access:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(position:access:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(position:)"],"title":"Creating a location"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(address:position:)"},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation/init(address:position:)":{"title":"init(address:position:)","url":"\/documentation\/nvdirectionkit\/nvibelocation\/init(address:position:)","kind":"symbol","abstract":[{"text":"Creates a location object with the specified address and position values.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"address"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(address:position:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"abstract":[{"text":"The address and coordinates of a location.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","url":"\/documentation\/nvdirectionkit\/nvibelocation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeLocation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeLocation"}],"type":"topic","kind":"symbol","title":"NVibeLocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation/init(position:)":{"title":"init(position:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(position:)","url":"\/documentation\/nvdirectionkit\/nvibelocation\/init(position:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":")","kind":"text"}],"abstract":[{"text":"Creates a location object with the specified position values.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation/init(address:position:access:)":{"title":"init(address:position:access:)","url":"\/documentation\/nvdirectionkit\/nvibelocation\/init(address:position:access:)","kind":"symbol","abstract":[{"text":"Creates a location object with the specified address, position and access values.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"address","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"access"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(address:position:access:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation/init(position:access:)":{"title":"init(position:access:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation\/init(position:access:)","url":"\/documentation\/nvdirectionkit\/nvibelocation\/init(position:access:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"access"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Creates a location object with the specified position and access values.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","value":"NVibeLocation","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"text":"NVibeLocation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeLocation"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}