{"metadata":{"title":"nextMultimodalStep","role":"symbol","modules":[{"name":"NVDirectionKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"nextMultimodalStep","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeMultimodalStep","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"s:14NVDirectionKit19NVibeTransitionDataC18nextMultimodalStepAA0cgH0CSgvp","roleHeading":"Instance Property","symbolKind":"property"},"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/nextMultimodalStep","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextMultimodalStep"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","text":"NVibeMultimodalStep"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibetransitiondata\/nextmultimodalstep"]}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData"]]},"seeAlsoSections":[{"title":"Getting the transition data attributes","anchor":"Getting-the-transition-data-attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/previousMultimodalStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/currentMultimodalStep"],"generated":true}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeTransitionData","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeTransitionData","kind":"identifier"}],"title":"NVibeTransitionData","abstract":[{"text":"The transition data for walking route.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData/nextMultimodalStep":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/nextMultimodalStep","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextMultimodalStep"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","text":"NVibeMultimodalStep"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata\/nextmultimodalstep","title":"nextMultimodalStep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"abstract":[{"text":"The multimodal step inside multimodal route.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeMultimodalStep","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeMultimodalStep","kind":"identifier"}],"title":"NVibeMultimodalStep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","role":"symbol","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData/previousMultimodalStep":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/previousMultimodalStep","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"previousMultimodalStep","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeMultimodalStep","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata\/previousmultimodalstep","title":"previousMultimodalStep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData/currentMultimodalStep":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/currentMultimodalStep","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentMultimodalStep","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeMultimodalStep","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata\/currentmultimodalstep","title":"currentMultimodalStep"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/title","value":"NVibeTransitionData","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/fragments","value":[{"kind":"identifier","text":"NVibeTransitionData"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/navigatorTitle","value":[{"text":"NVibeTransitionData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title","value":"NVibeMultimodalStep","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments","value":[{"text":"NVibeMultimodalStep","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/navigatorTitle","value":[{"text":"NVibeMultimodalStep","kind":"identifier"}],"op":"replace"}]}]}