{"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibetransitiondata\/previousmultimodalstep"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData"]]},"metadata":{"title":"previousMultimodalStep","externalID":"s:14NVDirectionKit19NVibeTransitionDataC22previousMultimodalStepAA0cgH0CSgvp","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"NVDirectionKit"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"previousMultimodalStep","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeMultimodalStep","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep"},{"kind":"text","text":"?"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/previousMultimodalStep"},"seeAlsoSections":[{"anchor":"Getting-the-transition-data-attributes","generated":true,"title":"Getting the transition data attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/currentMultimodalStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/nextMultimodalStep"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousMultimodalStep"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","text":"NVibeMultimodalStep","kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"abstract":[{"text":"The multimodal step inside multimodal route.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeMultimodalStep","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeMultimodalStep","kind":"identifier"}],"title":"NVibeMultimodalStep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","role":"symbol","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData/nextMultimodalStep":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/nextMultimodalStep","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextMultimodalStep"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","text":"NVibeMultimodalStep"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata\/nextmultimodalstep","title":"nextMultimodalStep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData/previousMultimodalStep":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/previousMultimodalStep","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"previousMultimodalStep","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeMultimodalStep","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata\/previousmultimodalstep","title":"previousMultimodalStep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeTransitionData","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeTransitionData","kind":"identifier"}],"title":"NVibeTransitionData","abstract":[{"text":"The transition data for walking route.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData/currentMultimodalStep":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData\/currentMultimodalStep","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentMultimodalStep","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeMultimodalStep","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata\/currentmultimodalstep","title":"currentMultimodalStep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title","value":"NVibeMultimodalStep"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments","op":"replace","value":[{"text":"NVibeMultimodalStep","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NVibeMultimodalStep"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/navigatorTitle"},{"value":"NVibeTransitionData","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/fragments","value":[{"kind":"identifier","text":"NVibeTransitionData"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/navigatorTitle","value":[{"text":"NVibeTransitionData","kind":"identifier"}],"op":"replace"}]}]}