{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The information point along a route."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/Se","doc:\/\/com.nvibe.NVDirectionKit\/SE","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint","interfaceLanguage":"swift"},"metadata":{"title":"NVibeInformationPoint","roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeInformationPoint"}],"navigatorTitle":[{"text":"NVibeInformationPoint","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"NVDirectionKit"}],"externalID":"c:@M@NVDirectionKit@objc(cs)NVibeInformationPoint"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeInformationPoint","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint","isActive":true,"type":"reference"},{"text":" object contains a information, the position coordinate of the information point, the projection on the route of the information point.","type":"text"}]}],"kind":"content"}],"topicSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/information","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/position","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/projection"],"anchor":"Getting-the-information-point-attributes","title":"Getting the information point attributes"},{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/init(from:)"],"title":"Initializers","anchor":"Initializers","generated":true}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link"],"anchor":"Global","generated":true,"title":"Global"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibeinformationpoint"]},{"paths":["\/documentation\/nvdirectionkit\/nvibeinformationpoint"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint/projection":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"projection","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"kind":"symbol","role":"symbol","title":"projection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/projection","url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint\/projection","type":"topic","abstract":[]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation":{"title":"NVibeIndoorLocation","role":"symbol","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation","navigatorTitle":[{"text":"NVibeIndoorLocation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeIndoorLocation"}],"type":"topic","abstract":[{"type":"text","text":"The address and coordinates of a indoor location."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation"},"doc://com.nvibe.NVDirectionKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint":{"type":"topic","kind":"symbol","title":"NVibeInformationPoint","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeInformationPoint","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeInformationPoint"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint","abstract":[{"text":"The information point along a route.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/SE":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SE","title":"Swift.Encodable"},"doc://com.nvibe.NVDirectionKit/SH":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH","title":"Swift.Hashable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet":{"title":"SideStreet","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","navigatorTitle":[{"kind":"identifier","text":"SideStreet"}],"url":"\/documentation\/nvdirectionkit\/sidestreet","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The side of the street."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SideStreet","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","title":"NVibeObstacle","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeobstacle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NVibeObstacle","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeObstacle","kind":"identifier"}],"abstract":[{"type":"text","text":"The obstacle along a route."}]},"doc://com.nvibe.NVDirectionKit/Se":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/Se","title":"Swift.Decodable"},"doc://com.nvibe.NVDirectionKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.nvibe.NVDirectionKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject","title":"NSObject"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint/init(from:)":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/init(from:)","title":"init(from:)","url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint\/init(from:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint/position":{"title":"position","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint\/position","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"]","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/position"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint/information":{"title":"information","role":"symbol","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint\/information","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"information","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint\/information","type":"topic"},"doc://com.nvibe.NVDirectionKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/Link":{"navigatorTitle":[{"text":"Link","kind":"identifier"}],"title":"Link","url":"\/documentation\/nvdirectionkit\/link","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The link along an alternative walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Link"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"abstract":[{"text":"The address and coordinates of a location.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","url":"\/documentation\/nvdirectionkit\/nvibelocation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeLocation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeLocation"}],"type":"topic","kind":"symbol","title":"NVibeLocation"},"doc://com.nvibe.NVDirectionKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"NVibeInformationPoint","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"NVibeInformationPoint"}]},{"op":"replace","value":[{"text":"NVibeInformationPoint","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":null,"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"value":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Link"],"anchor":"Global","generated":true,"title":"Global"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeInformationPoint"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/title","value":"NVibeIndoorLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/fragments","value":[{"text":"NVibeIndoorLocation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/navigatorTitle","value":[{"text":"NVibeIndoorLocation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/title","value":"NVibeInformationPoint"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/fragments","value":[{"text":"NVibeInformationPoint","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/navigatorTitle","value":[{"text":"NVibeInformationPoint","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/title","op":"replace","value":"NVibeObstacle"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/fragments","value":[{"text":"NVibeObstacle","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NVibeObstacle"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/title","op":"replace","value":"Link"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/fragments","value":[{"text":"Link","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1Link\/navigatorTitle","value":[{"text":"Link","kind":"identifier"}]},{"op":"replace","value":"NVibeLocation","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"text":"NVibeLocation","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NVibeLocation"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/navigatorTitle","op":"replace"}]}]}