{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"NVibeWalkingInformation","roleHeading":"Class","navigatorTitle":[{"text":"NVibeWalkingInformation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeWalkingInformation"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@NVDirectionKit@objc(cs)NVibeWalkingInformation","modules":[{"name":"NVDirectionKit"}]},"abstract":[{"text":"The walking information describing a walking multimodal step.","type":"text"}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibewalkinginformation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nvdirectionkit\/nvibewalkinginformation"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation"]},{"title":"Conforms To","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","doc:\/\/com.nvibe.NVDirectionKit\/SQ","doc:\/\/com.nvibe.NVDirectionKit\/SH"],"type":"conformsTo","kind":"relationships"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeWalkingInformation","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation"},"topicSections":[{"title":"Getting the walking information attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/startAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/endAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/walkingMode","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode"],"anchor":"Getting-the-walking-information-attributes"},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/arrivalRef","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/departureRef","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/links","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/via"]}],"seeAlsoSections":[{"anchor":"MultimodalRoute","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError"],"title":"MultimodalRoute"}],"references":{"doc://com.nvibe.NVDirectionKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/via":{"abstract":[{"text":"The street name used by alternative walking multimodal step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/via","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"via"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"title":"via","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/via","role":"symbol","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation":{"title":"NVibeMultimodalStepInformation","navigatorTitle":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"The information describing a multimodal step.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeMultimodalStepInformation"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/walkingMode":{"abstract":[{"text":"The mode of the walking multimodal step.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"walkingMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeWalkingInformation","text":"NVibeWalkingInformation","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14NVDirectionKit23NVibeWalkingInformationC4ModeO","text":"Mode"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/walkingmode","kind":"symbol","title":"walkingMode","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/walkingMode","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError":{"type":"topic","url":"\/documentation\/nvdirectionkit\/multimodalerror","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultimodalError","kind":"identifier"}],"title":"MultimodalError","abstract":[{"text":"Constants that describe error related to multimodal route calculation.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError","navigatorTitle":[{"text":"MultimodalError","kind":"identifier"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/SH":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/endAddress":{"abstract":[{"type":"text","text":"The  end location of the walking multimodal step."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endAddress","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeLocation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","kind":"typeIdentifier"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/endaddress","kind":"symbol","title":"endAddress","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/endAddress","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"abstract":[{"text":"The multimodal step inside multimodal route.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeMultimodalStep","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeMultimodalStep","kind":"identifier"}],"title":"NVibeMultimodalStep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","role":"symbol","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/objc(pl)NSObject":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeMultimodalRoute"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","kind":"symbol","navigatorTitle":[{"text":"NVibeMultimodalRoute","kind":"identifier"}],"title":"NVibeMultimodalRoute","url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute","abstract":[{"type":"text","text":"The multimodal route received when requesting multimodal route."}],"type":"topic","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/startAddress":{"role":"symbol","kind":"symbol","abstract":[{"text":"The  start location of the walking multimodal step.","type":"text"}],"title":"startAddress","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startAddress"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/startAddress","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/startaddress"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/Mode":{"role":"symbol","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/mode","abstract":[{"type":"text","text":"Constants that describe the mode of the walking multimodal step."}],"title":"NVibeWalkingInformation.Mode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode","type":"topic","navigatorTitle":[{"text":"Mode","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/links":{"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/links","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"links","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)Link","text":"Link","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"title":"links","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/links","type":"topic","abstract":[{"type":"text","text":"The links used by alternative walking multimodal step."}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/departureRef":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The indoor map id before the walking multimodal step."}],"title":"departureRef","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"departureRef","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/departureRef","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/departureref"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation":{"abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"kind":"symbol","title":"NVibeWalkingInformation","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeWalkingInformation","kind":"identifier"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation","role":"symbol","navigatorTitle":[{"text":"NVibeWalkingInformation","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s7CVarArgP","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation":{"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation","title":"NVibeTransitInformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeTransitInformation"}],"abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitInformation"}]},"doc://com.nvibe.NVDirectionKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitionData":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeTransitionData","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeTransitionData","kind":"identifier"}],"title":"NVibeTransitionData","abstract":[{"text":"The transition data for walking route.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData","url":"\/documentation\/nvdirectionkit\/nvibetransitiondata"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/arrivalRef":{"role":"symbol","kind":"symbol","abstract":[{"text":"The indoor map id after the walking multimodal step.","type":"text"}],"title":"arrivalRef","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arrivalRef","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/arrivalRef","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/arrivalref"},"doc://com.nvibe.NVDirectionKit/SQ":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"NVibeWalkingInformation","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"NVibeWalkingInformation","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"NVibeWalkingInformation","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitionData"],"anchor":"MultimodalRoute","generated":true,"title":"MultimodalRoute"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeWalkingInformation","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStepInformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","text":"NVibeMultimodalStepInformation"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"NVibeMultimodalStepInformation","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"NVibeMultimodalStepInformation"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeMultimodalStepInformation"}]},{"value":"NVibeMultimodalStep","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title"},{"op":"replace","value":[{"kind":"identifier","text":"NVibeMultimodalStep"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments"},{"value":[{"text":"NVibeMultimodalStep","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/title","value":"NVibeMultimodalRoute"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/fragments","value":[{"text":"NVibeMultimodalRoute","kind":"identifier"}]},{"value":[{"text":"NVibeMultimodalRoute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/title","value":"NVibeWalkingInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/fragments","value":[{"text":"NVibeWalkingInformation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/navigatorTitle","value":[{"text":"NVibeWalkingInformation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/title","value":"NVibeTransitInformation"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/fragments","value":[{"text":"NVibeTransitInformation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeTransitInformation"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/title","value":"NVibeTransitionData"},{"op":"replace","value":[{"kind":"identifier","text":"NVibeTransitionData"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/fragments"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitionData\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeTransitionData"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}