{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getTransitInformation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"NVibeTransitInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation"},{"kind":"text","text":"?"}],"role":"symbol","modules":[{"name":"NVDirectionKit"}],"roleHeading":"Instance Method","title":"getTransitInformation()","symbolKind":"method","externalID":"s:14NVDirectionKit30NVibeMultimodalStepInformationC010getTransitF0AA0chF0CSgyF"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/getTransitInformation()"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation"]]},"abstract":[{"text":"Returns a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation"},{"type":"text","text":" describing the multimodal step."}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/mode-swift.property","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/getWalkingInformation()","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/Mode-swift.enum"],"title":"Getting the multimodal step information attributes","generated":true,"anchor":"Getting-the-multimodal-step-information-attributes"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getTransitInformation"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"NVibeTransitInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","isActive":true,"type":"reference"},{"type":"text","text":" if the multimodal step is a transit multimodal step or "},{"code":"nil","type":"codeVoice"},{"text":" if it is not.","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/gettransitinformation()"]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation/Mode-swift.enum":{"title":"NVibeMultimodalStepInformation.Mode","kind":"symbol","abstract":[{"type":"text","text":"Constants that describe the mode of the multimodal step."}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/mode-swift.enum","navigatorTitle":[{"text":"Mode","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/Mode-swift.enum","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation/getTransitInformation()":{"title":"getTransitInformation()","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Returns a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","type":"reference"},{"type":"text","text":" describing the multimodal step."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getTransitInformation","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"NVibeTransitInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeTransitInformation","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/gettransitinformation()","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/getTransitInformation()"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation/mode-swift.property":{"title":"mode","kind":"symbol","abstract":[{"text":"The mode of the multimodal step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/mode-swift.property","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/mode-swift.property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mode","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeMultimodalStepInformation","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStepInformation","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"s:14NVDirectionKit30NVibeMultimodalStepInformationC4ModeO"}],"type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation":{"title":"NVibeMultimodalStepInformation","navigatorTitle":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"The information describing a multimodal step.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeMultimodalStepInformation"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation/getWalkingInformation()":{"title":"getWalkingInformation()","kind":"symbol","abstract":[{"type":"text","text":"Returns a "},{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","isActive":true,"type":"reference"},{"type":"text","text":" describing the multimodal step."}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation\/getwalkinginformation()","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation\/getWalkingInformation()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getWalkingInformation"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeWalkingInformation","text":"NVibeWalkingInformation"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation":{"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation","title":"NVibeTransitInformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeTransitInformation"}],"abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitInformation"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation":{"abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"kind":"symbol","title":"NVibeWalkingInformation","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeWalkingInformation","kind":"identifier"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation","role":"symbol","navigatorTitle":[{"text":"NVibeWalkingInformation","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"NVibeMultimodalStepInformation","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/title","op":"replace"},{"value":[{"text":"NVibeMultimodalStepInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NVibeMultimodalStepInformation"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/title","value":"NVibeTransitInformation","op":"replace"},{"value":[{"kind":"identifier","text":"NVibeTransitInformation"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeTransitInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/title","value":"NVibeWalkingInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/fragments","value":[{"kind":"identifier","text":"NVibeWalkingInformation"}]},{"value":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/navigatorTitle"}]}]}