{"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/distance"},"seeAlsoSections":[{"generated":true,"title":"Getting the multimodal route attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/startAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/endAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/duration","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/steps"],"anchor":"Getting-the-multimodal-route-attributes"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibemultimodalroute\/distance"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"externalID":"s:14NVDirectionKit20NVibeMultimodalRouteC8distanceSdvp","symbolKind":"property","role":"symbol","modules":[{"name":"NVDirectionKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"distance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"distance"},"abstract":[{"type":"text","text":"The distance in meter of the multimodal route."}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeMultimodalRoute"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","kind":"symbol","navigatorTitle":[{"text":"NVibeMultimodalRoute","kind":"identifier"}],"title":"NVibeMultimodalRoute","url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute","abstract":[{"type":"text","text":"The multimodal route received when requesting multimodal route."}],"type":"topic","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute/startAddress":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/startAddress","url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute\/startaddress","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"}],"role":"symbol","kind":"symbol","title":"startAddress","abstract":[{"type":"text","text":"The start location of the multimodal route."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute/duration":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The duration in second of the multimodal route."}],"kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/duration","title":"duration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute\/duration"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute/distance":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"distance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/distance","abstract":[{"text":"The distance in meter of the multimodal route.","type":"text"}],"kind":"symbol","title":"distance","url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute\/distance"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute/steps":{"role":"symbol","type":"topic","abstract":[{"text":"The list of step of the multimodal route.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/steps","title":"steps","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"steps","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NVibeMultimodalStep","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute\/steps"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute/endAddress":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endAddress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/endAddress","abstract":[{"text":"The end location of the multimodal route.","type":"text"}],"kind":"symbol","title":"endAddress","url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute\/endaddress"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/title","value":"NVibeMultimodalRoute"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/fragments","value":[{"text":"NVibeMultimodalRoute","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/navigatorTitle","value":[{"text":"NVibeMultimodalRoute","kind":"identifier"}]}]}]}