{"abstract":[{"text":"The walking outdoor with links mode.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"LINKS","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode\/LINKS"},"sections":[],"metadata":{"modules":[{"name":"NVDirectionKit"}],"title":"NVibeWalkingInformation.Mode.LINKS","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LINKS"}],"roleHeading":"Case","externalID":"s:14NVDirectionKit23NVibeWalkingInformationC4ModeO5LINKSyA2EmF","symbolKind":"case"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibewalkinginformation\/mode\/links"]}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/Mode/LINKS":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"LINKS","kind":"identifier"}],"title":"NVibeWalkingInformation.Mode.LINKS","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/mode\/links","abstract":[{"type":"text","text":"The walking outdoor with links mode."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode\/LINKS","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/Mode":{"role":"symbol","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/mode","abstract":[{"type":"text","text":"Constants that describe the mode of the walking multimodal step."}],"title":"NVibeWalkingInformation.Mode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode","type":"topic","navigatorTitle":[{"text":"Mode","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation":{"abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"kind":"symbol","title":"NVibeWalkingInformation","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeWalkingInformation","kind":"identifier"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation","role":"symbol","navigatorTitle":[{"text":"NVibeWalkingInformation","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"NVibeWalkingInformation","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/title"},{"value":[{"text":"NVibeWalkingInformation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/fragments"},{"value":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}