{"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibewalkinginformation\/mode\/transit_change"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode\/TRANSIT_CHANGE"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"TRANSIT_CHANGE","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","symbolKind":"case","title":"NVibeWalkingInformation.Mode.TRANSIT_CHANGE","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"TRANSIT_CHANGE","kind":"identifier"}],"modules":[{"name":"NVDirectionKit"}],"externalID":"s:14NVDirectionKit23NVibeWalkingInformationC4ModeO14TRANSIT_CHANGEyA2EmF"},"abstract":[{"text":"The walking transit change mode.","type":"text"}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/Mode":{"role":"symbol","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/mode","abstract":[{"type":"text","text":"Constants that describe the mode of the walking multimodal step."}],"title":"NVibeWalkingInformation.Mode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode","type":"topic","navigatorTitle":[{"text":"Mode","kind":"identifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation/Mode/TRANSIT_CHANGE":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation\/Mode\/TRANSIT_CHANGE","title":"NVibeWalkingInformation.Mode.TRANSIT_CHANGE","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation\/mode\/transit_change","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"TRANSIT_CHANGE","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The walking transit change mode."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation":{"abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"kind":"symbol","title":"NVibeWalkingInformation","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeWalkingInformation","kind":"identifier"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation","role":"symbol","navigatorTitle":[{"text":"NVibeWalkingInformation","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/title","op":"replace","value":"NVibeWalkingInformation"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/fragments","value":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/navigatorTitle","value":[{"text":"NVibeWalkingInformation","kind":"identifier"}]}]}]}