{"metadata":{"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"NVDirectionKit"}]},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/Mode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/Mode\/Equatable-Implementations"},"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/Mode\/!=(_:_:)"],"anchor":"Operators","title":"Operators"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibetransitinformation\/mode\/equatable-implementations"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/Mode/!=(_:_:)":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/Mode\/!=(_:_:)","title":"!=(_:_:)","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/mode\/!=(_:_:)","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation":{"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibetransitinformation","title":"NVibeTransitInformation","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeTransitInformation"}],"abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitInformation"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation/Mode":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation\/Mode","type":"topic","abstract":[{"type":"text","text":"Constants that describe the mode of the transit multimodal step."}],"url":"\/documentation\/nvdirectionkit\/nvibetransitinformation\/mode","navigatorTitle":[{"text":"Mode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"NVibeTransitInformation.Mode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/title","value":"NVibeTransitInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/fragments","value":[{"text":"NVibeTransitInformation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeTransitInformation"}]}]}]}