{"kind":"symbol","abstract":[{"type":"text","text":"The alternative geometry (encoded with an accuracy of 6) of the walking route."}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute"]]},"metadata":{"title":"alternativeGeometry","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"alternativeGeometry","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","externalID":"s:14NVDirectionKit10NVibeRouteC19alternativeGeometrySSSgvp","modules":[{"name":"NVDirectionKit"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"alternativeGeometry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/alternativeGeometry"},"seeAlsoSections":[{"title":"Getting the walking route attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/startAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/endAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/distance","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/duration","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/legs","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/geometry","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/coordinates","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/option"],"anchor":"Getting-the-walking-route-attributes","generated":true}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nviberoute\/alternativegeometry"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/legs":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"legs"},{"text":": [","kind":"text"},{"text":"NVibeLeg","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLeg"},{"kind":"text","text":"]"}],"kind":"symbol","role":"symbol","url":"\/documentation\/nvdirectionkit\/nviberoute\/legs","title":"legs","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/legs","abstract":[{"text":"The list of leg of the walking route.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/option":{"type":"topic","kind":"symbol","title":"option","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"option","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeRouteOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeRouteOption"}],"url":"\/documentation\/nvdirectionkit\/nviberoute\/option","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/option","abstract":[{"type":"text","text":"The option of the walking route."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"type":"topic","title":"NVDirectionKit","kind":"symbol","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.5.0","type":"text"}],"url":"\/documentation\/nvdirectionkit","role":"collection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/duration":{"url":"\/documentation\/nvdirectionkit\/nviberoute\/duration","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/duration","kind":"symbol","abstract":[{"type":"text","text":"The duration in second of the walking route."}],"title":"duration","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/alternativeGeometry":{"url":"\/documentation\/nvdirectionkit\/nviberoute\/alternativegeometry","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alternativeGeometry"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/alternativeGeometry","kind":"symbol","abstract":[{"type":"text","text":"The alternative geometry (encoded with an accuracy of 6) of the walking route."}],"title":"alternativeGeometry","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/endAddress":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/endAddress","url":"\/documentation\/nvdirectionkit\/nviberoute\/endaddress","title":"endAddress","abstract":[{"text":"The end location of the walking route.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"endAddress","kind":"identifier"},{"kind":"text","text":": "},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"navigatorTitle":[{"text":"NVibeRoute","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NVibeRoute","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeRoute"}],"url":"\/documentation\/nvdirectionkit\/nviberoute","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","abstract":[{"type":"text","text":"The walking route received when requesting walking route."}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/geometry":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"geometry"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/geometry","kind":"symbol","title":"geometry","abstract":[{"type":"text","text":"The geometry (encoded with an accuracy of 6) of the walking route."}],"role":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/geometry"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/startAddress":{"abstract":[{"type":"text","text":"The start location of the walking route."}],"title":"startAddress","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/startAddress","url":"\/documentation\/nvdirectionkit\/nviberoute\/startaddress","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/distance":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/distance","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"distance","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"distance","kind":"symbol","role":"symbol","abstract":[{"text":"The distance in meter of the walking route.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nviberoute\/distance"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/coordinates":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"coordinates","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":"]"}],"role":"symbol","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nviberoute\/coordinates","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/coordinates","title":"coordinates","abstract":[{"text":"The list of coordinates representing the walking route (decoded geometry).","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"NVibeRoute","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments","value":[{"kind":"identifier","text":"NVibeRoute"}],"op":"replace"},{"value":[{"text":"NVibeRoute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}