{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibemultimodalstep\/iswalkingtransitchangestep()"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"text":"Returns a Boolean value indicating wheter the multimodal step is a walking transit change multimodal step.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isWalkingTransitChangeStep","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}]},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":" if the multimodal step is a walking transit change multimodal step or "},{"type":"codeVoice","code":"false"},{"text":" if it is not.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/isWalkingTransitChangeStep()"},"metadata":{"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","externalID":"s:14NVDirectionKit19NVibeMultimodalStepC022isWalkingTransitChangeE0SbyF","modules":[{"name":"NVDirectionKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isWalkingTransitChangeStep"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isWalkingTransitChangeStep()"},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"abstract":[{"text":"The multimodal step inside multimodal route.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NVibeMultimodalStep","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeMultimodalStep","kind":"identifier"}],"title":"NVibeMultimodalStep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","role":"symbol","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep/isWalkingTransitChangeStep()":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Returns a Boolean value indicating wheter the multimodal step is a walking transit change multimodal step."}],"title":"isWalkingTransitChangeStep()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isWalkingTransitChangeStep","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep\/isWalkingTransitChangeStep()","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep\/iswalkingtransitchangestep()"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title","value":"NVibeMultimodalStep"},{"value":[{"text":"NVibeMultimodalStep","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/navigatorTitle","value":[{"text":"NVibeMultimodalStep","kind":"identifier"}]}]}]}