{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"NVDirectionKit provides services to obtain route and multimodal route (route including transit)."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"},{"type":"text","text":" singleton object to retrieve different route between two locations."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nvdirectionkit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nvdirectionkit"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"kind":"symbol","metadata":{"role":"collection","title":"NVDirectionKit","roleHeading":"Framework","symbolKind":"module","externalID":"NVDirectionKit","modules":[{"name":"NVDirectionKit"}],"platforms":[{"name":"iOS","introducedAt":"13.0"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]},{"title":"Global","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet"]},{"title":"Route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError"]},{"title":"MultimodalRoute","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError"]},{"title":"Extended Modules","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/CoreLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Foundation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Swift"]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/SideStreet":{"role":"symbol","title":"SideStreet","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SideStreet"}],"abstract":[{"type":"text","text":"The side of the street."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/SideStreet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SideStreet"}],"url":"\/documentation\/nvdirectionkit\/sidestreet"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeWalkingInformation":{"role":"symbol","title":"NVibeWalkingInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeWalkingInformation"}],"abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeWalkingInformation"}],"url":"\/documentation\/nvdirectionkit\/nvibewalkinginformation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVPhoneStateDetection":{"role":"symbol","title":"NVPhoneStateDetection","fragments":[{"kind":"identifier","text":"NVPhoneStateDetection"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVPhoneStateDetection","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvphonestatedetection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"role":"symbol","title":"NVibeRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRoute"}],"abstract":[{"type":"text","text":"The walking route received when requesting walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRoute"}],"url":"\/documentation\/nvdirectionkit\/nviberoute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/CoreLocation":{"role":"collection","title":"CoreLocation","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/CoreLocation","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/corelocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStepInformation":{"role":"symbol","title":"NVibeMultimodalStepInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalStepInformation"}],"abstract":[{"type":"text","text":"The information describing a multimodal step."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalStepInformation"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstepinformation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/RouteError":{"role":"symbol","title":"RouteError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteError"}],"abstract":[{"type":"text","text":"Constants that describe error related to walking route calculation."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/RouteError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RouteError"}],"url":"\/documentation\/nvdirectionkit\/routeerror"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeObstacle":{"role":"symbol","title":"NVibeObstacle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeObstacle"}],"abstract":[{"type":"text","text":"The obstacle along a route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeObstacle"}],"url":"\/documentation\/nvdirectionkit\/nvibeobstacle"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/GetRoute":{"role":"article","title":"Getting walking route","abstract":[{"type":"text","text":"Retrieve a walking route between two locations."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/getroute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"role":"symbol","title":"NVibeMultimodalStep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalStep"}],"abstract":[{"type":"text","text":"The multimodal step inside multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalStep"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVSDKTokenValidation":{"role":"symbol","title":"NVSDKTokenValidation","fragments":[{"kind":"identifier","text":"NVSDKTokenValidation"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVSDKTokenValidation","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvsdktokenvalidation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation":{"role":"symbol","title":"NVibeIndoorLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeIndoorLocation"}],"abstract":[{"type":"text","text":"The address and coordinates of a indoor location."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeIndoorLocation"}],"url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/Swift":{"role":"collection","title":"Swift","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Swift","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/swift"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/MultimodalError":{"role":"symbol","title":"MultimodalError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultimodalError"}],"abstract":[{"type":"text","text":"Constants that describe error related to multimodal route calculation."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/MultimodalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultimodalError"}],"url":"\/documentation\/nvdirectionkit\/multimodalerror"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVPhoneDirection":{"role":"symbol","title":"NVPhoneDirection","fragments":[{"kind":"identifier","text":"NVPhoneDirection"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVPhoneDirection","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvphonedirection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirectionKitVersionString":{"role":"symbol","title":"NVDirectionKitVersionString","fragments":[{"kind":"identifier","text":"NVDirectionKitVersionString"}],"abstract":[{"type":"text","text":"Project version string for NVDirectionKit."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirectionKitVersionString","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirectionkitversionstring"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIntersection":{"role":"symbol","title":"NVibeIntersection","fragments":[{"kind":"identifier","text":"NVibeIntersection"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIntersection","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibeintersection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/Foundation":{"role":"collection","title":"Foundation","abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/Foundation","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/foundation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeVibration":{"role":"symbol","title":"NVibeVibration","fragments":[{"kind":"identifier","text":"NVibeVibration"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeVibration","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibevibration"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg":{"role":"symbol","title":"NVibeLeg","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeLeg"}],"abstract":[{"type":"text","text":"The walking leg inside walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeLeg"}],"url":"\/documentation\/nvdirectionkit\/nvibeleg"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"role":"symbol","title":"NVibeStep","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeStep"}],"abstract":[{"type":"text","text":"The walking step inside walking leg."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"url":"\/documentation\/nvdirectionkit\/nvibestep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirection":{"role":"symbol","title":"NVDirection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVDirection"}],"abstract":[{"type":"text","text":"The object you use to mainly request route and multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVDirection"}],"url":"\/documentation\/nvdirectionkit\/nvdirection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/GetMultimodalRoute":{"role":"article","title":"Getting multimodal route","abstract":[{"type":"text","text":"Retrieve a multimodal route including transit between two locations."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/getmultimodalroute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuverDetail":{"role":"symbol","title":"NVibeManeuverDetail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeManeuverDetail"}],"abstract":[{"type":"text","text":"The detail inside maneuver."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeManeuverDetail"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuverdetail"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute":{"role":"symbol","title":"NVibeMultimodalRoute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalRoute"}],"abstract":[{"type":"text","text":"The multimodal route received when requesting multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeMultimodalRoute"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLocation":{"role":"symbol","title":"NVibeLocation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeLocation"}],"abstract":[{"type":"text","text":"The address and coordinates of a location."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeLocation"}],"url":"\/documentation\/nvdirectionkit\/nvibelocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver":{"role":"symbol","title":"NVibeManeuver","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeManeuver"}],"abstract":[{"type":"text","text":"The maneuver of the walking step."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeManeuver"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRouteOption":{"role":"symbol","title":"NVibeRouteOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeRouteOption"}],"abstract":[{"type":"text","text":"The option for walking route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRouteOption"}],"url":"\/documentation\/nvdirectionkit\/nviberouteoption"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","title":"NVDirectionKit","abstract":[{"type":"text","text":"Obtain route and multimodal route from N-Vibe."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeTransitInformation":{"role":"symbol","title":"NVibeTransitInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeTransitInformation"}],"abstract":[{"type":"text","text":"The walking information describing a walking multimodal step."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeTransitInformation"}],"url":"\/documentation\/nvdirectionkit\/nvibetransitinformation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeProjection":{"role":"symbol","title":"NVibeProjection","fragments":[{"kind":"identifier","text":"NVibeProjection"}],"abstract":[],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeProjection","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibeprojection"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/GetStarted":{"role":"article","title":"Get started","abstract":[{"type":"text","text":"Configure your app to be able to use the framework."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","kind":"article","type":"topic","url":"\/documentation\/nvdirectionkit\/getstarted"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVDirectionKitVersionNumber":{"role":"symbol","title":"NVDirectionKitVersionNumber","fragments":[{"kind":"identifier","text":"NVDirectionKitVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for NVDirectionKit."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirectionKitVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvdirectionkitversionnumber"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetStarted","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/GetMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirection"]},{"title":"Global","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeObstacle"]},{"title":"Route","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRouteOption"]},{"title":"MultimodalRoute","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStepInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeWalkingInformation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeTransitInformation"]},{"title":"Classes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVPhoneDirection","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVPhoneStateDetection","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVSDKTokenValidation","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIntersection","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeProjection","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeVibration"]},{"title":"Variables","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirectionKitVersionNumber","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVDirectionKitVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/title","value":"NVibeWalkingInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeWalkingInformation\/fragments","value":[{"kind":"identifier","text":"NVibeWalkingInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title","value":"NVibeRoute"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments","value":[{"kind":"identifier","text":"NVibeRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/title","value":"NVibeMultimodalStepInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStepInformation\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalStepInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/title","value":"NVibeObstacle"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeObstacle\/fragments","value":[{"kind":"identifier","text":"NVibeObstacle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title","value":"NVibeMultimodalStep"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalStep"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/title","value":"NVibeIndoorLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/fragments","value":[{"kind":"identifier","text":"NVibeIndoorLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/title","value":"NVibeLeg"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/fragments","value":[{"kind":"identifier","text":"NVibeLeg"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","value":"NVibeStep"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments","value":[{"kind":"identifier","text":"NVibeStep"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/title","value":"NVDirection"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVDirection\/fragments","value":[{"kind":"identifier","text":"NVDirection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/title","value":"NVibeManeuverDetail"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/fragments","value":[{"kind":"identifier","text":"NVibeManeuverDetail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/title","value":"NVibeMultimodalRoute"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalRoute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/title","value":"NVibeLocation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLocation\/fragments","value":[{"kind":"identifier","text":"NVibeLocation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/title","value":"NVibeManeuver"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/fragments","value":[{"kind":"identifier","text":"NVibeManeuver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/title","value":"NVibeRouteOption"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRouteOption\/fragments","value":[{"kind":"identifier","text":"NVibeRouteOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/title","value":"NVibeTransitInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeTransitInformation\/fragments","value":[{"kind":"identifier","text":"NVibeTransitInformation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}