{"metadata":{"role":"symbol","externalID":"s:14NVDirectionKit20NVibeMultimodalRouteC5stepsSayAA0cD4StepCGvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"steps","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NVibeMultimodalStep","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"steps","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"NVDirectionKit"}]},"kind":"symbol","abstract":[{"text":"The list of step of the multimodal route.","type":"text"}],"sections":[],"seeAlsoSections":[{"generated":true,"title":"Getting the multimodal route attributes","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/startAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/endAddress","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/distance","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/duration"],"anchor":"Getting-the-multimodal-route-attributes"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/steps","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"steps","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","text":"NVibeMultimodalStep","kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibemultimodalroute\/steps"]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalStep":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalStep","url":"\/documentation\/nvdirectionkit\/nvibemultimodalstep","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NVibeMultimodalStep","kind":"identifier"}],"navigatorTitle":[{"text":"NVibeMultimodalStep","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The multimodal step inside multimodal route.","type":"text"}],"type":"topic","title":"NVibeMultimodalStep"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"type":"topic","title":"NVDirectionKit","kind":"symbol","abstract":[{"inlineContent":[{"text":"Version:","type":"text"}],"type":"strong"},{"text":" 0.5.0","type":"text"}],"url":"\/documentation\/nvdirectionkit","role":"collection","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute/distance":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"distance"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"title":"distance","kind":"symbol","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute\/distance","abstract":[{"text":"The distance in meter of the multimodal route.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/distance","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute/startAddress":{"role":"symbol","kind":"symbol","type":"topic","title":"startAddress","abstract":[{"text":"The start location of the multimodal route.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/startAddress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"startAddress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation","text":"NVibeLocation","kind":"typeIdentifier"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute\/startaddress"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute/steps":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"steps","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeMultimodalStep","kind":"typeIdentifier","text":"NVibeMultimodalStep"},{"kind":"text","text":"]"}],"title":"steps","kind":"symbol","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute\/steps","abstract":[{"type":"text","text":"The list of step of the multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/steps","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute/duration":{"role":"symbol","kind":"symbol","type":"topic","title":"duration","abstract":[{"type":"text","text":"The duration in second of the multimodal route."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute\/duration"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute":{"type":"topic","title":"NVibeMultimodalRoute","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeMultimodalRoute"}],"kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute","role":"symbol","navigatorTitle":[{"text":"NVibeMultimodalRoute","kind":"identifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute","abstract":[{"text":"The multimodal route received when requesting multimodal route.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeMultimodalRoute/endAddress":{"kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeMultimodalRoute\/endAddress","title":"endAddress","abstract":[{"text":"The end location of the multimodal route.","type":"text"}],"type":"topic","url":"\/documentation\/nvdirectionkit\/nvibemultimodalroute\/endaddress","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"endAddress"},{"text":": ","kind":"text"},{"text":"NVibeLocation","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeLocation"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/title","value":"NVibeMultimodalStep","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalStep"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalStep\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeMultimodalStep"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/title","value":"NVibeMultimodalRoute","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/fragments","value":[{"kind":"identifier","text":"NVibeMultimodalRoute"}],"op":"replace"},{"value":[{"text":"NVibeMultimodalRoute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeMultimodalRoute\/navigatorTitle"}]}]}