{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibeleg\/distance"]}],"sections":[],"abstract":[{"type":"text","text":"The distance in meter of the walking leg."}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg"]]},"metadata":{"externalID":"s:14NVDirectionKit8NVibeLegC8distanceSdvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"distance"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"modules":[{"name":"NVDirectionKit"}],"title":"distance","role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"seeAlsoSections":[{"title":"Getting the walking leg attributes","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg\/duration","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg\/steps"],"anchor":"Getting-the-walking-leg-attributes"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg\/distance"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"distance"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg/duration":{"role":"symbol","kind":"symbol","abstract":[{"text":"The duration in second of the walking leg.","type":"text"}],"title":"duration","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg\/duration","url":"\/documentation\/nvdirectionkit\/nvibeleg\/duration"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg/distance":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The distance in meter of the walking leg."}],"title":"distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"distance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg\/distance","url":"\/documentation\/nvdirectionkit\/nvibeleg\/distance"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg/steps":{"url":"\/documentation\/nvdirectionkit\/nvibeleg\/steps","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg\/steps","title":"steps","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"steps"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NVibeStep","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeStep"},{"text":"]","kind":"text"}],"abstract":[{"text":"The list of step of the walking leg.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg":{"abstract":[{"type":"text","text":"The walking leg inside walking route."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NVibeLeg","kind":"identifier"}],"url":"\/documentation\/nvdirectionkit\/nvibeleg","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","kind":"symbol","title":"NVibeLeg","navigatorTitle":[{"kind":"identifier","text":"NVibeLeg"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/title","value":"NVibeLeg"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/fragments","op":"replace","value":[{"kind":"identifier","text":"NVibeLeg"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NVibeLeg"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}