{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibeleg\/steps"]}],"kind":"symbol","abstract":[{"text":"The list of step of the walking leg.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"steps"},{"kind":"text","text":": ["},{"text":"NVibeStep","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeStep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg"]]},"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg\/steps","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","externalID":"s:14NVDirectionKit8NVibeLegC5stepsSayAA0C4StepCGvp","title":"steps","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"steps","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeStep","text":"NVibeStep"},{"kind":"text","text":"]"}],"role":"symbol","modules":[{"name":"NVDirectionKit"}],"roleHeading":"Instance Property"},"seeAlsoSections":[{"title":"Getting the walking leg attributes","anchor":"Getting-the-walking-leg-attributes","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg\/distance","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg\/duration"]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg/distance":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The distance in meter of the walking leg."}],"title":"distance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"distance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg\/distance","url":"\/documentation\/nvdirectionkit\/nvibeleg\/distance"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg":{"abstract":[{"type":"text","text":"The walking leg inside walking route."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NVibeLeg","kind":"identifier"}],"url":"\/documentation\/nvdirectionkit\/nvibeleg","role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg","kind":"symbol","title":"NVibeLeg","navigatorTitle":[{"kind":"identifier","text":"NVibeLeg"}],"type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg/steps":{"url":"\/documentation\/nvdirectionkit\/nvibeleg\/steps","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg\/steps","title":"steps","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"steps"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NVibeStep","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeStep"},{"text":"]","kind":"text"}],"abstract":[{"text":"The list of step of the walking leg.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeStep","kind":"identifier"}],"role":"symbol","title":"NVibeStep","navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","abstract":[{"text":"The walking step inside walking leg.","type":"text"}],"kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeLeg/duration":{"role":"symbol","kind":"symbol","abstract":[{"text":"The duration in second of the walking leg.","type":"text"}],"title":"duration","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeLeg\/duration","url":"\/documentation\/nvdirectionkit\/nvibeleg\/duration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"NVibeLeg","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/title"},{"value":[{"kind":"identifier","text":"NVibeLeg"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeLeg\/navigatorTitle","value":[{"text":"NVibeLeg","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","op":"replace","value":"NVibeStep"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments","op":"replace","value":[{"kind":"identifier","text":"NVibeStep"}]},{"value":[{"kind":"identifier","text":"NVibeStep"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/navigatorTitle","op":"replace"}]}]}