{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","externalID":"s:14NVDirectionKit19NVibeManeuverDetailC4nameSSSgvp","roleHeading":"Instance Property","modules":[{"name":"NVDirectionKit"}],"title":"name","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"property"},"abstract":[{"type":"text","text":"The name of the street along the single maneuver."}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail\/name","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"anchor":"Getting-the-maneuver-detail-attributes","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail\/type","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail\/modifier","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail\/instruction"],"title":"Getting the maneuver detail attributes"}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibemaneuverdetail\/name"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuverDetail":{"title":"NVibeManeuverDetail","url":"\/documentation\/nvdirectionkit\/nvibemaneuverdetail","kind":"symbol","abstract":[{"text":"The detail inside maneuver.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail","navigatorTitle":[{"text":"NVibeManeuverDetail","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NVibeManeuverDetail","kind":"identifier"}],"type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuverDetail/name":{"abstract":[{"type":"text","text":"The name of the street along the single maneuver."}],"title":"name","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuverdetail\/name","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail\/name"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuverDetail/type":{"kind":"symbol","title":"type","url":"\/documentation\/nvdirectionkit\/nvibemaneuverdetail\/type","role":"symbol","abstract":[{"text":"The type of the single maneuver.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail\/type"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuverDetail/modifier":{"kind":"symbol","title":"modifier","url":"\/documentation\/nvdirectionkit\/nvibemaneuverdetail\/modifier","role":"symbol","abstract":[{"text":"The modifier of the single maneuver.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail\/modifier"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuverDetail/instruction":{"abstract":[{"text":"The instruction of the single maneuver.","type":"text"}],"title":"instruction","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuverdetail\/instruction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"instruction"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuverDetail\/instruction"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/title","op":"replace","value":"NVibeManeuverDetail"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/fragments","value":[{"text":"NVibeManeuverDetail","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuverDetail\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeManeuverDetail"}],"op":"replace"}]}]}