{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"toGPX"},{"text":"(","kind":"text"},{"text":"speed","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":" = 5000.0) -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"speed","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The speed of the GPS in m\/s. The default value of this property is "},{"code":"5000","type":"codeVoice"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"code":"String","type":"codeVoice"},{"text":" value representing the GPX of the walking route.","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/toGPX(speed:)"},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nviberoute\/togpx(speed:)"]}],"abstract":[{"text":"Returns a ","type":"text"},{"type":"codeVoice","code":"String"},{"type":"text","text":" value representing the GPX of the walking route."}],"sections":[],"metadata":{"externalID":"s:14NVDirectionKit10NVibeRouteC5toGPX5speedSSSd_tF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toGPX","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"speed"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"toGPX(speed:)","roleHeading":"Instance Method","modules":[{"name":"NVDirectionKit"}],"symbolKind":"method","role":"symbol"},"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute/toGPX(speed:)":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nviberoute\/togpx(speed:)","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute\/toGPX(speed:)","abstract":[{"text":"Returns a ","type":"text"},{"code":"String","type":"codeVoice"},{"type":"text","text":" value representing the GPX of the walking route."}],"title":"toGPX(speed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toGPX"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"speed"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeRoute":{"abstract":[{"text":"The walking route received when requesting walking route.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NVibeRoute"}],"url":"\/documentation\/nvdirectionkit\/nviberoute","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeRoute"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeRoute","kind":"symbol","title":"NVibeRoute"}},"variantOverrides":[{"patch":[{"value":"NVibeRoute","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/title","op":"replace"},{"op":"replace","value":[{"text":"NVibeRoute","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/fragments"},{"value":[{"kind":"identifier","text":"NVibeRoute"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeRoute\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}