{"metadata":{"symbolKind":"property","externalID":"s:14NVDirectionKit9NVibeStepC11coordinatesSaySo22CLLocationCoordinate2DVGvp","modules":[{"name":"NVDirectionKit"}],"title":"coordinates","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinates"},{"kind":"text","text":": ["},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":"]"}],"role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep"]]},"abstract":[{"text":"The list of coordinates representing the walking step (decoded geometry).","type":"text"}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibestep\/coordinates"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"coordinates","kind":"identifier"},{"text":": [","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/coordinates","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/distance","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/duration","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/maneuver","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/walkingSide","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/streetName","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/geometry","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/obstacles"],"generated":true,"anchor":"Getting-the-walking-step-attributes","title":"Getting the walking step attributes"}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/geometry":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"geometry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","title":"geometry","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep\/geometry","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/geometry","kind":"symbol","abstract":[{"text":"The geometry (encoded with an accuracy of 6) of the walking step.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/maneuver":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/maneuver","title":"maneuver","url":"\/documentation\/nvdirectionkit\/nvibestep\/maneuver","abstract":[{"text":"The maneuver of the walking step.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maneuver","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuver","kind":"typeIdentifier","text":"NVibeManeuver"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/obstacles":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"obstacles"},{"text":": [","kind":"text"},{"text":"NVibeObstacle","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeObstacle","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"role":"symbol","title":"obstacles","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep\/obstacles","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/obstacles","kind":"symbol","abstract":[{"text":"The obstacles along the walking step.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/duration":{"abstract":[{"text":"The duration in second of the walking step.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"duration"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"duration","url":"\/documentation\/nvdirectionkit\/nvibestep\/duration","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/duration","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeStep","kind":"identifier"}],"role":"symbol","title":"NVibeStep","navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","abstract":[{"text":"The walking step inside walking leg.","type":"text"}],"kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/coordinates":{"title":"coordinates","kind":"symbol","abstract":[{"text":"The list of coordinates representing the walking step (decoded geometry).","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibestep\/coordinates","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/coordinates","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinates","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":"]","kind":"text"}],"role":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/distance":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"distance","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","title":"distance","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep\/distance","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/distance","abstract":[{"text":"The distance in meter of the walking step.","type":"text"}],"kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/walkingSide":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"walkingSide"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/walkingSide","title":"walkingSide","type":"topic","kind":"symbol","abstract":[{"text":"The side of the street along the walking step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibestep\/walkingside"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/streetName":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"streetName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"streetName","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/streetName","kind":"symbol","abstract":[{"text":"The name of the street along the walking step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibestep\/streetname"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","value":"NVibeStep"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments","value":[{"kind":"identifier","text":"NVibeStep"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NVibeStep"}]}]}]}