{"sections":[],"metadata":{"externalID":"s:14NVDirectionKit9NVibeStepC8durationSdvp","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"duration","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"roleHeading":"Instance Property","modules":[{"name":"NVDirectionKit"}],"title":"duration","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"duration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"The duration in second of the walking step."}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/distance","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/maneuver","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/walkingSide","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/streetName","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/geometry","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/coordinates","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/obstacles"],"title":"Getting the walking step attributes","anchor":"Getting-the-walking-step-attributes","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibestep\/duration"]}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/duration"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/streetName":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"streetName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"streetName","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/streetName","kind":"symbol","abstract":[{"text":"The name of the street along the walking step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibestep\/streetname"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/geometry":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"geometry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","title":"geometry","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep\/geometry","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/geometry","kind":"symbol","abstract":[{"text":"The geometry (encoded with an accuracy of 6) of the walking step.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/maneuver":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/maneuver","title":"maneuver","url":"\/documentation\/nvdirectionkit\/nvibestep\/maneuver","abstract":[{"text":"The maneuver of the walking step.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maneuver","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuver","kind":"typeIdentifier","text":"NVibeManeuver"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/obstacles":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"obstacles"},{"text":": [","kind":"text"},{"text":"NVibeObstacle","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeObstacle","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"role":"symbol","title":"obstacles","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep\/obstacles","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/obstacles","kind":"symbol","abstract":[{"text":"The obstacles along the walking step.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/coordinates":{"title":"coordinates","kind":"symbol","abstract":[{"text":"The list of coordinates representing the walking step (decoded geometry).","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibestep\/coordinates","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/coordinates","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinates","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":"]","kind":"text"}],"role":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeStep","kind":"identifier"}],"role":"symbol","title":"NVibeStep","navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","abstract":[{"text":"The walking step inside walking leg.","type":"text"}],"kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/distance":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"distance","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","title":"distance","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep\/distance","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/distance","abstract":[{"text":"The distance in meter of the walking step.","type":"text"}],"kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/duration":{"abstract":[{"text":"The duration in second of the walking step.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"duration"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"duration","url":"\/documentation\/nvdirectionkit\/nvibestep\/duration","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/duration","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/walkingSide":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"walkingSide"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/walkingSide","title":"walkingSide","type":"topic","kind":"symbol","abstract":[{"text":"The side of the street along the walking step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibestep\/walkingside"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","value":"NVibeStep","op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments","op":"replace","value":[{"text":"NVibeStep","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/navigatorTitle","value":[{"kind":"identifier","text":"NVibeStep"}],"op":"replace"}]}]}