{"kind":"symbol","metadata":{"role":"symbol","externalID":"s:14NVDirectionKit9NVibeStepC17informationPointsSayAA0C16InformationPointCGSgvp","roleHeading":"Instance Property","modules":[{"name":"NVDirectionKit"}],"title":"informationPoints","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"informationPoints"},{"text":": [","kind":"text"},{"text":"NVibeInformationPoint","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeInformationPoint","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"symbolKind":"property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"informationPoints","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeInformationPoint","text":"NVibeInformationPoint","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibestep\/informationpoints"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/informationPoints"},"abstract":[{"type":"text","text":"The information points along the walking step."}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/informationPoints":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"informationPoints"},{"text":": [","kind":"text"},{"text":"NVibeInformationPoint","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeInformationPoint","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"title":"informationPoints","abstract":[{"text":"The information points along the walking step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibestep\/informationpoints","type":"topic","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/informationPoints","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeInformationPoint":{"type":"topic","kind":"symbol","title":"NVibeInformationPoint","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeInformationPoint","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NVibeInformationPoint"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeInformationPoint","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeinformationpoint","abstract":[{"text":"The information point along a route.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeStep","kind":"identifier"}],"role":"symbol","title":"NVibeStep","navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","abstract":[{"text":"The walking step inside walking leg.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"NVibeInformationPoint","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/title"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/fragments","value":[{"kind":"identifier","text":"NVibeInformationPoint"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeInformationPoint\/navigatorTitle","op":"replace","value":[{"text":"NVibeInformationPoint","kind":"identifier"}]},{"value":"NVibeStep","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","op":"replace"},{"op":"replace","value":[{"text":"NVibeStep","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/navigatorTitle","value":[{"text":"NVibeStep","kind":"identifier"}]}]}]}