{"kind":"symbol","metadata":{"title":"maneuver","externalID":"s:14NVDirectionKit9NVibeStepC8maneuverAA0C8ManeuverCvp","modules":[{"name":"NVDirectionKit"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maneuver"},{"text":": ","kind":"text"},{"text":"NVibeManeuver","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuver"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/maneuver"},"abstract":[{"type":"text","text":"The maneuver of the walking step."}],"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep"]]},"seeAlsoSections":[{"title":"Getting the walking step attributes","anchor":"Getting-the-walking-step-attributes","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/distance","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/duration","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/walkingSide","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/streetName","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/geometry","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/coordinates","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/obstacles"]}],"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibestep\/maneuver"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maneuver"},{"text":": ","kind":"text"},{"text":"NVibeManeuver","kind":"typeIdentifier","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuver"}]}]}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/coordinates":{"title":"coordinates","kind":"symbol","abstract":[{"text":"The list of coordinates representing the walking step (decoded geometry).","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibestep\/coordinates","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/coordinates","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coordinates","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":"]","kind":"text"}],"role":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/obstacles":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"obstacles"},{"text":": [","kind":"text"},{"text":"NVibeObstacle","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeObstacle","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"role":"symbol","title":"obstacles","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep\/obstacles","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/obstacles","kind":"symbol","abstract":[{"text":"The obstacles along the walking step.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/walkingSide":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"walkingSide"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/walkingSide","title":"walkingSide","type":"topic","kind":"symbol","abstract":[{"text":"The side of the street along the walking step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibestep\/walkingside"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/streetName":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"streetName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"streetName","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/streetName","kind":"symbol","abstract":[{"text":"The name of the street along the walking step.","type":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibestep\/streetname"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/distance":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"distance","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","title":"distance","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep\/distance","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/distance","abstract":[{"text":"The distance in meter of the walking step.","type":"text"}],"kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NVibeStep","kind":"identifier"}],"role":"symbol","title":"NVibeStep","navigatorTitle":[{"kind":"identifier","text":"NVibeStep"}],"type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep","abstract":[{"text":"The walking step inside walking leg.","type":"text"}],"kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/geometry":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"geometry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","title":"geometry","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibestep\/geometry","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/geometry","kind":"symbol","abstract":[{"text":"The geometry (encoded with an accuracy of 6) of the walking step.","type":"text"}]},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/maneuver":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/maneuver","title":"maneuver","url":"\/documentation\/nvdirectionkit\/nvibestep\/maneuver","abstract":[{"text":"The maneuver of the walking step.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maneuver","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuver","kind":"typeIdentifier","text":"NVibeManeuver"}],"role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeStep/duration":{"abstract":[{"text":"The duration in second of the walking step.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"duration"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"duration","url":"\/documentation\/nvdirectionkit\/nvibestep\/duration","kind":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeStep\/duration","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeManeuver"}],"navigatorTitle":[{"text":"NVibeManeuver","kind":"identifier"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver","abstract":[{"text":"The maneuver of the walking step.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","type":"topic","title":"NVibeManeuver"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/title","op":"replace","value":"NVibeStep"},{"value":[{"text":"NVibeStep","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/fragments"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeStep\/navigatorTitle","value":[{"text":"NVibeStep","kind":"identifier"}],"op":"replace"},{"value":"NVibeManeuver","op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/fragments","value":[{"kind":"identifier","text":"NVibeManeuver"}]},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/navigatorTitle","value":[{"text":"NVibeManeuver","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}