{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/nvdirectionkit\/nvibemaneuver\/type"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/type","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","modules":[{"name":"NVDirectionKit"}],"externalID":"s:14NVDirectionKit13NVibeManeuverC4typeSSvp","title":"type","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver"]]},"sections":[],"abstract":[{"text":"The type of the maneuver.","type":"text"}],"seeAlsoSections":[{"title":"Getting the maneuver attributes","generated":true,"identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/modifier","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/bearing_before","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/bearing_after","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/coordinate","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/instruction","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/turn_direction","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/details"],"anchor":"Getting-the-maneuver-attributes"}],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/instruction":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/instruction","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"instruction"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":"The instruction of the maneuver.","type":"text"}],"title":"instruction","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/instruction","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/modifier":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/modifier","abstract":[{"text":"The modifier of the maneuver.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/modifier","type":"topic","title":"modifier"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/turn_direction":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/turn_direction","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"turn_direction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"?","kind":"text"}],"abstract":[{"text":"The turn direction in hour of the maneuver.","type":"text"}],"title":"turn_direction","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/turn_direction","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/details":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"details"},{"kind":"text","text":": ["},{"text":"NVibeManeuverDetail","kind":"typeIdentifier","preciseIdentifier":"c:@M@NVDirectionKit@objc(cs)NVibeManeuverDetail"},{"text":"]","kind":"text"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/details","abstract":[{"text":"The details of the maneuver.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/details","type":"topic","title":"details"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/type":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":"The type of the maneuver.","type":"text"}],"title":"type","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/type","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/coordinate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinate"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/coordinate","abstract":[{"text":"The coordinate of the maneuver.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/coordinate","type":"topic","title":"coordinate"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/bearing_after":{"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/bearing_after","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bearing_after"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"abstract":[{"text":"The angle after the maneuver.","type":"text"}],"title":"bearing_after","role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/bearing_after","kind":"symbol","type":"topic"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NVibeManeuver"}],"navigatorTitle":[{"text":"NVibeManeuver","kind":"identifier"}],"url":"\/documentation\/nvdirectionkit\/nvibemaneuver","abstract":[{"text":"The maneuver of the walking step.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver","type":"topic","title":"NVibeManeuver"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeManeuver/bearing_before":{"url":"\/documentation\/nvdirectionkit\/nvibemaneuver\/bearing_before","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bearing_before"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeManeuver\/bearing_before","abstract":[{"type":"text","text":"The angle before the maneuver."}],"title":"bearing_before"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/title","value":"NVibeManeuver"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/fragments","value":[{"kind":"identifier","text":"NVibeManeuver"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeManeuver\/navigatorTitle","op":"replace","value":[{"text":"NVibeManeuver","kind":"identifier"}]}]}]}