{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nvdirectionkit\/nvibeindoorlocation\/init(address:position:access:floor:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"address","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"access","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"text":"floor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The address of the indoor location.","type":"text"}]}],"name":"address"},{"content":[{"inlineContent":[{"text":"The position coordinate of the indoor location.","type":"text"}],"type":"paragraph"}],"name":"position"},{"name":"access","content":[{"type":"paragraph","inlineContent":[{"text":"The access coordinate of the indoor location.","type":"text"}]}]},{"name":"floor","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The floor of the indoor location."}]}]}]}],"identifier":{"url":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/init(address:position:access:floor:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"NVDirectionKit"}],"title":"init(address:position:access:floor:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"address","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","kind":"typeIdentifier","text":"CLLocationCoordinate2D"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"access"},{"kind":"text","text":": "},{"text":"CLLocationCoordinate2D","kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"floor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"externalID":"s:14NVDirectionKit19NVibeIndoorLocationC7address8position6access5floorACSS_So22CLLocationCoordinate2DVAISitcfc","roleHeading":"Initializer","symbolKind":"init","role":"symbol"},"seeAlsoSections":[{"generated":true,"anchor":"Creating-an-indoor-location","title":"Creating an indoor location","identifiers":["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/init(address:position:floor:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/init(position:access:floor:)","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/init(position:floor:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation"]]},"abstract":[{"type":"text","text":"Creates a indoor location object with the specified address, position, access and floor values."}],"sections":[],"references":{"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation/init(address:position:floor:)":{"abstract":[{"text":"Creates a indoor location object with the specified address, position and floor values.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/init(address:position:floor:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation\/init(address:position:floor:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"address","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"floor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(address:position:floor:)","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation":{"title":"NVibeIndoorLocation","role":"symbol","kind":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation","navigatorTitle":[{"text":"NVibeIndoorLocation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NVibeIndoorLocation"}],"type":"topic","abstract":[{"type":"text","text":"The address and coordinates of a indoor location."}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation/init(address:position:access:floor:)":{"abstract":[{"text":"Creates a indoor location object with the specified address, position, access and floor values.","type":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/init(address:position:access:floor:)","kind":"symbol","type":"topic","url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation\/init(address:position:access:floor:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"address","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"access","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"floor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(address:position:access:floor:)","role":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit":{"role":"collection","url":"\/documentation\/nvdirectionkit","title":"NVDirectionKit","identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit","abstract":[{"inlineContent":[{"type":"text","text":"Version:"}],"type":"strong"},{"type":"text","text":" 0.6.1"}],"type":"topic","kind":"symbol"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation/init(position:floor:)":{"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation\/init(position:floor:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Creates a indoor location object with the specified position and floor values."}],"title":"init(position:floor:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"text":"floor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/init(position:floor:)"},"doc://com.nvibe.NVDirectionKit/documentation/NVDirectionKit/NVibeIndoorLocation/init(position:access:floor:)":{"role":"symbol","url":"\/documentation\/nvdirectionkit\/nvibeindoorlocation\/init(position:access:floor:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Creates a indoor location object with the specified position, access and floor values."}],"title":"init(position:access:floor:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D"},{"kind":"text","text":", "},{"kind":"externalParam","text":"access"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"floor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.nvibe.NVDirectionKit\/documentation\/NVDirectionKit\/NVibeIndoorLocation\/init(position:access:floor:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/title","value":"NVibeIndoorLocation"},{"path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/fragments","op":"replace","value":[{"kind":"identifier","text":"NVibeIndoorLocation"}]},{"value":[{"text":"NVibeIndoorLocation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nvibe.NVDirectionKit~1documentation~1NVDirectionKit~1NVibeIndoorLocation\/navigatorTitle"}]}]}